use serde::{Deserialize, Serialize};
use serde_with::serde_as;
use starknet_core::serde::unsigned_field_element::UfeHex;
use starknet_crypto::Felt;

// Commitment values for the Traces component. Used to generate a commitment by "reading" these
// values from the channel.
#[serde_as]
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct UnsentCommitment {
    #[serde_as(as = "UfeHex")]
    original: Felt,
    #[serde_as(as = "UfeHex")]
    interaction: Felt,
}

// Commitment for the Traces component.
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct Commitment {
    // Commitment to the first trace.
    original: cairovm_verifier_commitment::table::types::Commitment,
    // The interaction elements that were sent to the prover after the first trace commitment (e.g.
    // memory interaction).
    // interaction_elements: InteractionElements,
    // Commitment to the second (interaction) trace.
    interaction: cairovm_verifier_commitment::table::types::Commitment,
}

// Responses for queries to the AIR commitment.
// The queries are usually generated by the next component down the line (e.g. FRI).
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct Decommitment {
    // Responses for queries to the original trace.
    original: cairovm_verifier_commitment::table::types::Decommitment,
    // Responses for queries to the interaction trace.
    interaction: cairovm_verifier_commitment::table::types::Decommitment,
}

// A witness for a decommitment of the AIR traces over queries.
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct Witness {
    original: cairovm_verifier_commitment::table::types::Witness,
    interaction: cairovm_verifier_commitment::table::types::Witness,
}

// Configuration for the Traces component.
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct Config {
    original: cairovm_verifier_commitment::table::types::Config,
    interaction: cairovm_verifier_commitment::table::types::Config,
}
