use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DynamicParams {
    pub add_mod_a0_suboffset: usize,
    pub add_mod_a1_suboffset: usize,
    pub add_mod_a2_suboffset: usize,
    pub add_mod_a3_suboffset: usize,
    pub add_mod_a_offset_suboffset: usize,
    pub add_mod_b0_suboffset: usize,
    pub add_mod_b1_suboffset: usize,
    pub add_mod_b2_suboffset: usize,
    pub add_mod_b3_suboffset: usize,
    pub add_mod_b_offset_suboffset: usize,
    pub add_mod_c0_suboffset: usize,
    pub add_mod_c1_suboffset: usize,
    pub add_mod_c2_suboffset: usize,
    pub add_mod_c3_suboffset: usize,
    pub add_mod_c_offset_suboffset: usize,
    pub add_mod_carry1_bit_column: usize,
    pub add_mod_carry1_bit_offset: usize,
    pub add_mod_carry1_sign_column: usize,
    pub add_mod_carry1_sign_offset: usize,
    pub add_mod_carry2_bit_column: usize,
    pub add_mod_carry2_bit_offset: usize,
    pub add_mod_carry2_sign_column: usize,
    pub add_mod_carry2_sign_offset: usize,
    pub add_mod_carry3_bit_column: usize,
    pub add_mod_carry3_bit_offset: usize,
    pub add_mod_carry3_sign_column: usize,
    pub add_mod_carry3_sign_offset: usize,
    pub add_mod_n_suboffset: usize,
    pub add_mod_offsets_ptr_suboffset: usize,
    pub add_mod_p0_suboffset: usize,
    pub add_mod_p1_suboffset: usize,
    pub add_mod_p2_suboffset: usize,
    pub add_mod_p3_suboffset: usize,
    pub add_mod_row_ratio: usize,
    pub add_mod_sub_p_bit_column: usize,
    pub add_mod_sub_p_bit_offset: usize,
    pub add_mod_values_ptr_suboffset: usize,
    pub bitwise_diluted_var_pool_suboffset: usize,
    pub bitwise_row_ratio: usize,
    pub bitwise_trim_unpacking192_suboffset: usize,
    pub bitwise_trim_unpacking193_suboffset: usize,
    pub bitwise_trim_unpacking194_suboffset: usize,
    pub bitwise_trim_unpacking195_suboffset: usize,
    pub bitwise_var_pool_suboffset: usize,
    pub bitwise_x_or_y_suboffset: usize,
    pub cpu_decode_mem_inst_suboffset: usize,
    pub cpu_decode_off0_suboffset: usize,
    pub cpu_decode_off1_suboffset: usize,
    pub cpu_decode_off2_suboffset: usize,
    pub cpu_decode_opcode_range_check_column_column: usize,
    pub cpu_decode_opcode_range_check_column_offset: usize,
    pub cpu_operands_mem_dst_suboffset: usize,
    pub cpu_operands_mem_op0_suboffset: usize,
    pub cpu_operands_mem_op1_suboffset: usize,
    pub cpu_operands_ops_mul_column: usize,
    pub cpu_operands_ops_mul_offset: usize,
    pub cpu_operands_res_column: usize,
    pub cpu_operands_res_offset: usize,
    pub cpu_registers_ap_column: usize,
    pub cpu_registers_ap_offset: usize,
    pub cpu_registers_fp_column: usize,
    pub cpu_registers_fp_offset: usize,
    pub cpu_update_registers_update_pc_tmp0_column: usize,
    pub cpu_update_registers_update_pc_tmp0_offset: usize,
    pub cpu_update_registers_update_pc_tmp1_column: usize,
    pub cpu_update_registers_update_pc_tmp1_offset: usize,
    pub cpu_component_step: usize,
    pub diluted_check_cumulative_value_column: usize,
    pub diluted_check_cumulative_value_offset: usize,
    pub diluted_check_permutation_cum_prod0_column: usize,
    pub diluted_check_permutation_cum_prod0_offset: usize,
    pub diluted_check_permuted_values_column: usize,
    pub diluted_check_permuted_values_offset: usize,
    pub diluted_pool_column: usize,
    pub diluted_pool_offset: usize,
    pub diluted_units_row_ratio: usize,
    pub ec_op_doubled_points_x_column: usize,
    pub ec_op_doubled_points_x_offset: usize,
    pub ec_op_doubled_points_y_column: usize,
    pub ec_op_doubled_points_y_offset: usize,
    pub ec_op_doubling_slope_column: usize,
    pub ec_op_doubling_slope_offset: usize,
    pub ec_op_ec_subset_sum_bit_unpacking_prod_ones192_column: usize,
    pub ec_op_ec_subset_sum_bit_unpacking_prod_ones192_offset: usize,
    pub ec_op_ec_subset_sum_bit_unpacking_prod_ones196_column: usize,
    pub ec_op_ec_subset_sum_bit_unpacking_prod_ones196_offset: usize,
    pub ec_op_ec_subset_sum_partial_sum_x_column: usize,
    pub ec_op_ec_subset_sum_partial_sum_x_offset: usize,
    pub ec_op_ec_subset_sum_partial_sum_y_column: usize,
    pub ec_op_ec_subset_sum_partial_sum_y_offset: usize,
    pub ec_op_ec_subset_sum_selector_column: usize,
    pub ec_op_ec_subset_sum_selector_offset: usize,
    pub ec_op_ec_subset_sum_slope_column: usize,
    pub ec_op_ec_subset_sum_slope_offset: usize,
    pub ec_op_ec_subset_sum_x_diff_inv_column: usize,
    pub ec_op_ec_subset_sum_x_diff_inv_offset: usize,
    pub ec_op_m_suboffset: usize,
    pub ec_op_p_x_suboffset: usize,
    pub ec_op_p_y_suboffset: usize,
    pub ec_op_q_x_suboffset: usize,
    pub ec_op_q_y_suboffset: usize,
    pub ec_op_r_x_suboffset: usize,
    pub ec_op_r_y_suboffset: usize,
    pub ec_op_builtin_row_ratio: usize,
    pub ecdsa_message_suboffset: usize,
    pub ecdsa_pubkey_suboffset: usize,
    pub ecdsa_signature0_add_results_inv_column: usize,
    pub ecdsa_signature0_add_results_inv_offset: usize,
    pub ecdsa_signature0_add_results_slope_column: usize,
    pub ecdsa_signature0_add_results_slope_offset: usize,
    pub ecdsa_signature0_doubling_slope_column: usize,
    pub ecdsa_signature0_doubling_slope_offset: usize,
    pub ecdsa_signature0_exponentiate_generator_partial_sum_x_column: usize,
    pub ecdsa_signature0_exponentiate_generator_partial_sum_x_offset: usize,
    pub ecdsa_signature0_exponentiate_generator_partial_sum_y_column: usize,
    pub ecdsa_signature0_exponentiate_generator_partial_sum_y_offset: usize,
    pub ecdsa_signature0_exponentiate_generator_selector_column: usize,
    pub ecdsa_signature0_exponentiate_generator_selector_offset: usize,
    pub ecdsa_signature0_exponentiate_generator_slope_column: usize,
    pub ecdsa_signature0_exponentiate_generator_slope_offset: usize,
    pub ecdsa_signature0_exponentiate_generator_x_diff_inv_column: usize,
    pub ecdsa_signature0_exponentiate_generator_x_diff_inv_offset: usize,
    pub ecdsa_signature0_exponentiate_key_partial_sum_x_column: usize,
    pub ecdsa_signature0_exponentiate_key_partial_sum_x_offset: usize,
    pub ecdsa_signature0_exponentiate_key_partial_sum_y_column: usize,
    pub ecdsa_signature0_exponentiate_key_partial_sum_y_offset: usize,
    pub ecdsa_signature0_exponentiate_key_selector_column: usize,
    pub ecdsa_signature0_exponentiate_key_selector_offset: usize,
    pub ecdsa_signature0_exponentiate_key_slope_column: usize,
    pub ecdsa_signature0_exponentiate_key_slope_offset: usize,
    pub ecdsa_signature0_exponentiate_key_x_diff_inv_column: usize,
    pub ecdsa_signature0_exponentiate_key_x_diff_inv_offset: usize,
    pub ecdsa_signature0_extract_r_inv_column: usize,
    pub ecdsa_signature0_extract_r_inv_offset: usize,
    pub ecdsa_signature0_extract_r_slope_column: usize,
    pub ecdsa_signature0_extract_r_slope_offset: usize,
    pub ecdsa_signature0_key_points_x_column: usize,
    pub ecdsa_signature0_key_points_x_offset: usize,
    pub ecdsa_signature0_key_points_y_column: usize,
    pub ecdsa_signature0_key_points_y_offset: usize,
    pub ecdsa_signature0_q_x_squared_column: usize,
    pub ecdsa_signature0_q_x_squared_offset: usize,
    pub ecdsa_signature0_r_w_inv_column: usize,
    pub ecdsa_signature0_r_w_inv_offset: usize,
    pub ecdsa_signature0_z_inv_column: usize,
    pub ecdsa_signature0_z_inv_offset: usize,
    pub ecdsa_builtin_row_ratio: usize,
    pub keccak_input_output_suboffset: usize,
    pub keccak_keccak_diluted_column0_suboffset: usize,
    pub keccak_keccak_diluted_column1_suboffset: usize,
    pub keccak_keccak_diluted_column2_suboffset: usize,
    pub keccak_keccak_diluted_column3_suboffset: usize,
    pub keccak_keccak_parse_to_diluted_cumulative_sum_column: usize,
    pub keccak_keccak_parse_to_diluted_cumulative_sum_offset: usize,
    pub keccak_keccak_parse_to_diluted_final_reshaped_input_column: usize,
    pub keccak_keccak_parse_to_diluted_final_reshaped_input_offset: usize,
    pub keccak_keccak_parse_to_diluted_reshaped_intermediate_column: usize,
    pub keccak_keccak_parse_to_diluted_reshaped_intermediate_offset: usize,
    pub keccak_keccak_rotated_parity0_column: usize,
    pub keccak_keccak_rotated_parity0_offset: usize,
    pub keccak_keccak_rotated_parity1_column: usize,
    pub keccak_keccak_rotated_parity1_offset: usize,
    pub keccak_keccak_rotated_parity2_column: usize,
    pub keccak_keccak_rotated_parity2_offset: usize,
    pub keccak_keccak_rotated_parity3_column: usize,
    pub keccak_keccak_rotated_parity3_offset: usize,
    pub keccak_keccak_rotated_parity4_column: usize,
    pub keccak_keccak_rotated_parity4_offset: usize,
    pub keccak_row_ratio: usize,
    pub mem_pool_addr_column: usize,
    pub mem_pool_addr_offset: usize,
    pub mem_pool_value_column: usize,
    pub mem_pool_value_offset: usize,
    pub memory_multi_column_perm_perm_cum_prod0_column: usize,
    pub memory_multi_column_perm_perm_cum_prod0_offset: usize,
    pub memory_sorted_addr_column: usize,
    pub memory_sorted_addr_offset: usize,
    pub memory_sorted_value_column: usize,
    pub memory_sorted_value_offset: usize,
    pub memory_units_row_ratio: usize,
    pub mul_mod_a0_suboffset: usize,
    pub mul_mod_a1_suboffset: usize,
    pub mul_mod_a2_suboffset: usize,
    pub mul_mod_a3_suboffset: usize,
    pub mul_mod_a_offset_suboffset: usize,
    pub mul_mod_b0_suboffset: usize,
    pub mul_mod_b1_suboffset: usize,
    pub mul_mod_b2_suboffset: usize,
    pub mul_mod_b3_suboffset: usize,
    pub mul_mod_b_offset_suboffset: usize,
    pub mul_mod_c0_suboffset: usize,
    pub mul_mod_c1_suboffset: usize,
    pub mul_mod_c2_suboffset: usize,
    pub mul_mod_c3_suboffset: usize,
    pub mul_mod_c_offset_suboffset: usize,
    pub mul_mod_carry0_part0_suboffset: usize,
    pub mul_mod_carry0_part1_suboffset: usize,
    pub mul_mod_carry0_part2_suboffset: usize,
    pub mul_mod_carry0_part3_suboffset: usize,
    pub mul_mod_carry0_part4_suboffset: usize,
    pub mul_mod_carry0_part5_suboffset: usize,
    pub mul_mod_carry0_part6_suboffset: usize,
    pub mul_mod_carry1_part0_suboffset: usize,
    pub mul_mod_carry1_part1_suboffset: usize,
    pub mul_mod_carry1_part2_suboffset: usize,
    pub mul_mod_carry1_part3_suboffset: usize,
    pub mul_mod_carry1_part4_suboffset: usize,
    pub mul_mod_carry1_part5_suboffset: usize,
    pub mul_mod_carry1_part6_suboffset: usize,
    pub mul_mod_carry2_part0_suboffset: usize,
    pub mul_mod_carry2_part1_suboffset: usize,
    pub mul_mod_carry2_part2_suboffset: usize,
    pub mul_mod_carry2_part3_suboffset: usize,
    pub mul_mod_carry2_part4_suboffset: usize,
    pub mul_mod_carry2_part5_suboffset: usize,
    pub mul_mod_carry2_part6_suboffset: usize,
    pub mul_mod_carry3_part0_suboffset: usize,
    pub mul_mod_carry3_part1_suboffset: usize,
    pub mul_mod_carry3_part2_suboffset: usize,
    pub mul_mod_carry3_part3_suboffset: usize,
    pub mul_mod_carry3_part4_suboffset: usize,
    pub mul_mod_carry3_part5_suboffset: usize,
    pub mul_mod_carry3_part6_suboffset: usize,
    pub mul_mod_carry4_part0_suboffset: usize,
    pub mul_mod_carry4_part1_suboffset: usize,
    pub mul_mod_carry4_part2_suboffset: usize,
    pub mul_mod_carry4_part3_suboffset: usize,
    pub mul_mod_carry4_part4_suboffset: usize,
    pub mul_mod_carry4_part5_suboffset: usize,
    pub mul_mod_carry4_part6_suboffset: usize,
    pub mul_mod_carry5_part0_suboffset: usize,
    pub mul_mod_carry5_part1_suboffset: usize,
    pub mul_mod_carry5_part2_suboffset: usize,
    pub mul_mod_carry5_part3_suboffset: usize,
    pub mul_mod_carry5_part4_suboffset: usize,
    pub mul_mod_carry5_part5_suboffset: usize,
    pub mul_mod_carry5_part6_suboffset: usize,
    pub mul_mod_n_suboffset: usize,
    pub mul_mod_offsets_ptr_suboffset: usize,
    pub mul_mod_p0_suboffset: usize,
    pub mul_mod_p1_suboffset: usize,
    pub mul_mod_p2_suboffset: usize,
    pub mul_mod_p3_suboffset: usize,
    pub mul_mod_p_multiplier0_part0_suboffset: usize,
    pub mul_mod_p_multiplier0_part1_suboffset: usize,
    pub mul_mod_p_multiplier0_part2_suboffset: usize,
    pub mul_mod_p_multiplier0_part3_suboffset: usize,
    pub mul_mod_p_multiplier0_part4_suboffset: usize,
    pub mul_mod_p_multiplier0_part5_suboffset: usize,
    pub mul_mod_p_multiplier1_part0_suboffset: usize,
    pub mul_mod_p_multiplier1_part1_suboffset: usize,
    pub mul_mod_p_multiplier1_part2_suboffset: usize,
    pub mul_mod_p_multiplier1_part3_suboffset: usize,
    pub mul_mod_p_multiplier1_part4_suboffset: usize,
    pub mul_mod_p_multiplier1_part5_suboffset: usize,
    pub mul_mod_p_multiplier2_part0_suboffset: usize,
    pub mul_mod_p_multiplier2_part1_suboffset: usize,
    pub mul_mod_p_multiplier2_part2_suboffset: usize,
    pub mul_mod_p_multiplier2_part3_suboffset: usize,
    pub mul_mod_p_multiplier2_part4_suboffset: usize,
    pub mul_mod_p_multiplier2_part5_suboffset: usize,
    pub mul_mod_p_multiplier3_part0_suboffset: usize,
    pub mul_mod_p_multiplier3_part1_suboffset: usize,
    pub mul_mod_p_multiplier3_part2_suboffset: usize,
    pub mul_mod_p_multiplier3_part3_suboffset: usize,
    pub mul_mod_p_multiplier3_part4_suboffset: usize,
    pub mul_mod_p_multiplier3_part5_suboffset: usize,
    pub mul_mod_row_ratio: usize,
    pub mul_mod_values_ptr_suboffset: usize,
    pub num_columns_first: usize,
    pub num_columns_second: usize,
    pub orig_public_memory_suboffset: usize,
    pub pedersen_hash0_ec_subset_sum_bit_unpacking_prod_ones192_column: usize,
    pub pedersen_hash0_ec_subset_sum_bit_unpacking_prod_ones192_offset: usize,
    pub pedersen_hash0_ec_subset_sum_bit_unpacking_prod_ones196_column: usize,
    pub pedersen_hash0_ec_subset_sum_bit_unpacking_prod_ones196_offset: usize,
    pub pedersen_hash0_ec_subset_sum_partial_sum_x_column: usize,
    pub pedersen_hash0_ec_subset_sum_partial_sum_x_offset: usize,
    pub pedersen_hash0_ec_subset_sum_partial_sum_y_column: usize,
    pub pedersen_hash0_ec_subset_sum_partial_sum_y_offset: usize,
    pub pedersen_hash0_ec_subset_sum_selector_column: usize,
    pub pedersen_hash0_ec_subset_sum_selector_offset: usize,
    pub pedersen_hash0_ec_subset_sum_slope_column: usize,
    pub pedersen_hash0_ec_subset_sum_slope_offset: usize,
    pub pedersen_input0_suboffset: usize,
    pub pedersen_input1_suboffset: usize,
    pub pedersen_output_suboffset: usize,
    pub pedersen_builtin_row_ratio: usize,
    pub poseidon_param_0_input_output_suboffset: usize,
    pub poseidon_param_1_input_output_suboffset: usize,
    pub poseidon_param_2_input_output_suboffset: usize,
    pub poseidon_poseidon_full_rounds_state0_column: usize,
    pub poseidon_poseidon_full_rounds_state0_offset: usize,
    pub poseidon_poseidon_full_rounds_state0_squared_column: usize,
    pub poseidon_poseidon_full_rounds_state0_squared_offset: usize,
    pub poseidon_poseidon_full_rounds_state1_column: usize,
    pub poseidon_poseidon_full_rounds_state1_offset: usize,
    pub poseidon_poseidon_full_rounds_state1_squared_column: usize,
    pub poseidon_poseidon_full_rounds_state1_squared_offset: usize,
    pub poseidon_poseidon_full_rounds_state2_column: usize,
    pub poseidon_poseidon_full_rounds_state2_offset: usize,
    pub poseidon_poseidon_full_rounds_state2_squared_column: usize,
    pub poseidon_poseidon_full_rounds_state2_squared_offset: usize,
    pub poseidon_poseidon_partial_rounds_state0_column: usize,
    pub poseidon_poseidon_partial_rounds_state0_offset: usize,
    pub poseidon_poseidon_partial_rounds_state0_squared_column: usize,
    pub poseidon_poseidon_partial_rounds_state0_squared_offset: usize,
    pub poseidon_poseidon_partial_rounds_state1_column: usize,
    pub poseidon_poseidon_partial_rounds_state1_offset: usize,
    pub poseidon_poseidon_partial_rounds_state1_squared_column: usize,
    pub poseidon_poseidon_partial_rounds_state1_squared_offset: usize,
    pub poseidon_row_ratio: usize,
    pub range_check16_perm_cum_prod0_column: usize,
    pub range_check16_perm_cum_prod0_offset: usize,
    pub range_check16_sorted_column: usize,
    pub range_check16_sorted_offset: usize,
    pub range_check16_pool_column: usize,
    pub range_check16_pool_offset: usize,
    pub range_check96_builtin_inner_range_check0_suboffset: usize,
    pub range_check96_builtin_inner_range_check1_suboffset: usize,
    pub range_check96_builtin_inner_range_check2_suboffset: usize,
    pub range_check96_builtin_inner_range_check3_suboffset: usize,
    pub range_check96_builtin_inner_range_check4_suboffset: usize,
    pub range_check96_builtin_inner_range_check5_suboffset: usize,
    pub range_check96_builtin_mem_suboffset: usize,
    pub range_check96_builtin_row_ratio: usize,
    pub range_check_builtin_inner_range_check_suboffset: usize,
    pub range_check_builtin_mem_suboffset: usize,
    pub range_check_builtin_row_ratio: usize,
    pub range_check_units_row_ratio: usize,
    pub uses_add_mod_builtin: usize,
    pub uses_bitwise_builtin: usize,
    pub uses_ec_op_builtin: usize,
    pub uses_ecdsa_builtin: usize,
    pub uses_keccak_builtin: usize,
    pub uses_mul_mod_builtin: usize,
    pub uses_pedersen_builtin: usize,
    pub uses_poseidon_builtin: usize,
    pub uses_range_check96_builtin: usize,
    pub uses_range_check_builtin: usize,
}

use alloc::vec::Vec;

impl From<Vec<usize>> for DynamicParams {
    fn from(vec: Vec<usize>) -> Self {
        // Ensure the vector has the correct length
        assert_eq!(vec.len(), 340, "Vector length does not match the number of fields");

        Self {
            add_mod_a0_suboffset: vec[0],
            add_mod_a1_suboffset: vec[1],
            add_mod_a2_suboffset: vec[2],
            add_mod_a3_suboffset: vec[3],
            add_mod_a_offset_suboffset: vec[4],
            add_mod_b0_suboffset: vec[5],
            add_mod_b1_suboffset: vec[6],
            add_mod_b2_suboffset: vec[7],
            add_mod_b3_suboffset: vec[8],
            add_mod_b_offset_suboffset: vec[9],
            add_mod_c0_suboffset: vec[10],
            add_mod_c1_suboffset: vec[11],
            add_mod_c2_suboffset: vec[12],
            add_mod_c3_suboffset: vec[13],
            add_mod_c_offset_suboffset: vec[14],
            add_mod_carry1_bit_column: vec[15],
            add_mod_carry1_bit_offset: vec[16],
            add_mod_carry1_sign_column: vec[17],
            add_mod_carry1_sign_offset: vec[18],
            add_mod_carry2_bit_column: vec[19],
            add_mod_carry2_bit_offset: vec[20],
            add_mod_carry2_sign_column: vec[21],
            add_mod_carry2_sign_offset: vec[22],
            add_mod_carry3_bit_column: vec[23],
            add_mod_carry3_bit_offset: vec[24],
            add_mod_carry3_sign_column: vec[25],
            add_mod_carry3_sign_offset: vec[26],
            add_mod_n_suboffset: vec[27],
            add_mod_offsets_ptr_suboffset: vec[28],
            add_mod_p0_suboffset: vec[29],
            add_mod_p1_suboffset: vec[30],
            add_mod_p2_suboffset: vec[31],
            add_mod_p3_suboffset: vec[32],
            add_mod_row_ratio: vec[33],
            add_mod_sub_p_bit_column: vec[34],
            add_mod_sub_p_bit_offset: vec[35],
            add_mod_values_ptr_suboffset: vec[36],
            bitwise_diluted_var_pool_suboffset: vec[37],
            bitwise_row_ratio: vec[38],
            bitwise_trim_unpacking192_suboffset: vec[39],
            bitwise_trim_unpacking193_suboffset: vec[40],
            bitwise_trim_unpacking194_suboffset: vec[41],
            bitwise_trim_unpacking195_suboffset: vec[42],
            bitwise_var_pool_suboffset: vec[43],
            bitwise_x_or_y_suboffset: vec[44],
            cpu_decode_mem_inst_suboffset: vec[45],
            cpu_decode_off0_suboffset: vec[46],
            cpu_decode_off1_suboffset: vec[47],
            cpu_decode_off2_suboffset: vec[48],
            cpu_decode_opcode_range_check_column_column: vec[49],
            cpu_decode_opcode_range_check_column_offset: vec[50],
            cpu_operands_mem_dst_suboffset: vec[51],
            cpu_operands_mem_op0_suboffset: vec[52],
            cpu_operands_mem_op1_suboffset: vec[53],
            cpu_operands_ops_mul_column: vec[54],
            cpu_operands_ops_mul_offset: vec[55],
            cpu_operands_res_column: vec[56],
            cpu_operands_res_offset: vec[57],
            cpu_registers_ap_column: vec[58],
            cpu_registers_ap_offset: vec[59],
            cpu_registers_fp_column: vec[60],
            cpu_registers_fp_offset: vec[61],
            cpu_update_registers_update_pc_tmp0_column: vec[62],
            cpu_update_registers_update_pc_tmp0_offset: vec[63],
            cpu_update_registers_update_pc_tmp1_column: vec[64],
            cpu_update_registers_update_pc_tmp1_offset: vec[65],
            cpu_component_step: vec[66],
            diluted_check_cumulative_value_column: vec[67],
            diluted_check_cumulative_value_offset: vec[68],
            diluted_check_permutation_cum_prod0_column: vec[69],
            diluted_check_permutation_cum_prod0_offset: vec[70],
            diluted_check_permuted_values_column: vec[71],
            diluted_check_permuted_values_offset: vec[72],
            diluted_pool_column: vec[73],
            diluted_pool_offset: vec[74],
            diluted_units_row_ratio: vec[75],
            ec_op_doubled_points_x_column: vec[76],
            ec_op_doubled_points_x_offset: vec[77],
            ec_op_doubled_points_y_column: vec[78],
            ec_op_doubled_points_y_offset: vec[79],
            ec_op_doubling_slope_column: vec[80],
            ec_op_doubling_slope_offset: vec[81],
            ec_op_ec_subset_sum_bit_unpacking_prod_ones192_column: vec[82],
            ec_op_ec_subset_sum_bit_unpacking_prod_ones192_offset: vec[83],
            ec_op_ec_subset_sum_bit_unpacking_prod_ones196_column: vec[84],
            ec_op_ec_subset_sum_bit_unpacking_prod_ones196_offset: vec[85],
            ec_op_ec_subset_sum_partial_sum_x_column: vec[86],
            ec_op_ec_subset_sum_partial_sum_x_offset: vec[87],
            ec_op_ec_subset_sum_partial_sum_y_column: vec[88],
            ec_op_ec_subset_sum_partial_sum_y_offset: vec[89],
            ec_op_ec_subset_sum_selector_column: vec[90],
            ec_op_ec_subset_sum_selector_offset: vec[91],
            ec_op_ec_subset_sum_slope_column: vec[92],
            ec_op_ec_subset_sum_slope_offset: vec[93],
            ec_op_ec_subset_sum_x_diff_inv_column: vec[94],
            ec_op_ec_subset_sum_x_diff_inv_offset: vec[95],
            ec_op_m_suboffset: vec[96],
            ec_op_p_x_suboffset: vec[97],
            ec_op_p_y_suboffset: vec[98],
            ec_op_q_x_suboffset: vec[99],
            ec_op_q_y_suboffset: vec[100],
            ec_op_r_x_suboffset: vec[101],
            ec_op_r_y_suboffset: vec[102],
            ec_op_builtin_row_ratio: vec[103],
            ecdsa_message_suboffset: vec[104],
            ecdsa_pubkey_suboffset: vec[105],
            ecdsa_signature0_add_results_inv_column: vec[106],
            ecdsa_signature0_add_results_inv_offset: vec[107],
            ecdsa_signature0_add_results_slope_column: vec[108],
            ecdsa_signature0_add_results_slope_offset: vec[109],
            ecdsa_signature0_doubling_slope_column: vec[110],
            ecdsa_signature0_doubling_slope_offset: vec[111],
            ecdsa_signature0_exponentiate_generator_partial_sum_x_column: vec[112],
            ecdsa_signature0_exponentiate_generator_partial_sum_x_offset: vec[113],
            ecdsa_signature0_exponentiate_generator_partial_sum_y_column: vec[114],
            ecdsa_signature0_exponentiate_generator_partial_sum_y_offset: vec[115],
            ecdsa_signature0_exponentiate_generator_selector_column: vec[116],
            ecdsa_signature0_exponentiate_generator_selector_offset: vec[117],
            ecdsa_signature0_exponentiate_generator_slope_column: vec[118],
            ecdsa_signature0_exponentiate_generator_slope_offset: vec[119],
            ecdsa_signature0_exponentiate_generator_x_diff_inv_column: vec[120],
            ecdsa_signature0_exponentiate_generator_x_diff_inv_offset: vec[121],
            ecdsa_signature0_exponentiate_key_partial_sum_x_column: vec[122],
            ecdsa_signature0_exponentiate_key_partial_sum_x_offset: vec[123],
            ecdsa_signature0_exponentiate_key_partial_sum_y_column: vec[124],
            ecdsa_signature0_exponentiate_key_partial_sum_y_offset: vec[125],
            ecdsa_signature0_exponentiate_key_selector_column: vec[126],
            ecdsa_signature0_exponentiate_key_selector_offset: vec[127],
            ecdsa_signature0_exponentiate_key_slope_column: vec[128],
            ecdsa_signature0_exponentiate_key_slope_offset: vec[129],
            ecdsa_signature0_exponentiate_key_x_diff_inv_column: vec[130],
            ecdsa_signature0_exponentiate_key_x_diff_inv_offset: vec[131],
            ecdsa_signature0_extract_r_inv_column: vec[132],
            ecdsa_signature0_extract_r_inv_offset: vec[133],
            ecdsa_signature0_extract_r_slope_column: vec[134],
            ecdsa_signature0_extract_r_slope_offset: vec[135],
            ecdsa_signature0_key_points_x_column: vec[136],
            ecdsa_signature0_key_points_x_offset: vec[137],
            ecdsa_signature0_key_points_y_column: vec[138],
            ecdsa_signature0_key_points_y_offset: vec[139],
            ecdsa_signature0_q_x_squared_column: vec[140],
            ecdsa_signature0_q_x_squared_offset: vec[141],
            ecdsa_signature0_r_w_inv_column: vec[142],
            ecdsa_signature0_r_w_inv_offset: vec[143],
            ecdsa_signature0_z_inv_column: vec[144],
            ecdsa_signature0_z_inv_offset: vec[145],
            ecdsa_builtin_row_ratio: vec[146],
            keccak_input_output_suboffset: vec[147],
            keccak_keccak_diluted_column0_suboffset: vec[148],
            keccak_keccak_diluted_column1_suboffset: vec[149],
            keccak_keccak_diluted_column2_suboffset: vec[150],
            keccak_keccak_diluted_column3_suboffset: vec[151],
            keccak_keccak_parse_to_diluted_cumulative_sum_column: vec[152],
            keccak_keccak_parse_to_diluted_cumulative_sum_offset: vec[153],
            keccak_keccak_parse_to_diluted_final_reshaped_input_column: vec[154],
            keccak_keccak_parse_to_diluted_final_reshaped_input_offset: vec[155],
            keccak_keccak_parse_to_diluted_reshaped_intermediate_column: vec[156],
            keccak_keccak_parse_to_diluted_reshaped_intermediate_offset: vec[157],
            keccak_keccak_rotated_parity0_column: vec[158],
            keccak_keccak_rotated_parity0_offset: vec[159],
            keccak_keccak_rotated_parity1_column: vec[160],
            keccak_keccak_rotated_parity1_offset: vec[161],
            keccak_keccak_rotated_parity2_column: vec[162],
            keccak_keccak_rotated_parity2_offset: vec[163],
            keccak_keccak_rotated_parity3_column: vec[164],
            keccak_keccak_rotated_parity3_offset: vec[165],
            keccak_keccak_rotated_parity4_column: vec[166],
            keccak_keccak_rotated_parity4_offset: vec[167],
            keccak_row_ratio: vec[168],
            mem_pool_addr_column: vec[169],
            mem_pool_addr_offset: vec[170],
            mem_pool_value_column: vec[171],
            mem_pool_value_offset: vec[172],
            memory_multi_column_perm_perm_cum_prod0_column: vec[173],
            memory_multi_column_perm_perm_cum_prod0_offset: vec[174],
            memory_sorted_addr_column: vec[175],
            memory_sorted_addr_offset: vec[176],
            memory_sorted_value_column: vec[177],
            memory_sorted_value_offset: vec[178],
            memory_units_row_ratio: vec[179],
            mul_mod_a0_suboffset: vec[180],
            mul_mod_a1_suboffset: vec[181],
            mul_mod_a2_suboffset: vec[182],
            mul_mod_a3_suboffset: vec[183],
            mul_mod_a_offset_suboffset: vec[184],
            mul_mod_b0_suboffset: vec[185],
            mul_mod_b1_suboffset: vec[186],
            mul_mod_b2_suboffset: vec[187],
            mul_mod_b3_suboffset: vec[188],
            mul_mod_b_offset_suboffset: vec[189],
            mul_mod_c0_suboffset: vec[190],
            mul_mod_c1_suboffset: vec[191],
            mul_mod_c2_suboffset: vec[192],
            mul_mod_c3_suboffset: vec[193],
            mul_mod_c_offset_suboffset: vec[194],
            mul_mod_carry0_part0_suboffset: vec[195],
            mul_mod_carry0_part1_suboffset: vec[196],
            mul_mod_carry0_part2_suboffset: vec[197],
            mul_mod_carry0_part3_suboffset: vec[198],
            mul_mod_carry0_part4_suboffset: vec[199],
            mul_mod_carry0_part5_suboffset: vec[200],
            mul_mod_carry0_part6_suboffset: vec[201],
            mul_mod_carry1_part0_suboffset: vec[202],
            mul_mod_carry1_part1_suboffset: vec[203],
            mul_mod_carry1_part2_suboffset: vec[204],
            mul_mod_carry1_part3_suboffset: vec[205],
            mul_mod_carry1_part4_suboffset: vec[206],
            mul_mod_carry1_part5_suboffset: vec[207],
            mul_mod_carry1_part6_suboffset: vec[208],
            mul_mod_carry2_part0_suboffset: vec[209],
            mul_mod_carry2_part1_suboffset: vec[210],
            mul_mod_carry2_part2_suboffset: vec[211],
            mul_mod_carry2_part3_suboffset: vec[212],
            mul_mod_carry2_part4_suboffset: vec[213],
            mul_mod_carry2_part5_suboffset: vec[214],
            mul_mod_carry2_part6_suboffset: vec[215],
            mul_mod_carry3_part0_suboffset: vec[216],
            mul_mod_carry3_part1_suboffset: vec[217],
            mul_mod_carry3_part2_suboffset: vec[218],
            mul_mod_carry3_part3_suboffset: vec[219],
            mul_mod_carry3_part4_suboffset: vec[220],
            mul_mod_carry3_part5_suboffset: vec[221],
            mul_mod_carry3_part6_suboffset: vec[222],
            mul_mod_carry4_part0_suboffset: vec[223],
            mul_mod_carry4_part1_suboffset: vec[224],
            mul_mod_carry4_part2_suboffset: vec[225],
            mul_mod_carry4_part3_suboffset: vec[226],
            mul_mod_carry4_part4_suboffset: vec[227],
            mul_mod_carry4_part5_suboffset: vec[228],
            mul_mod_carry4_part6_suboffset: vec[229],
            mul_mod_carry5_part0_suboffset: vec[230],
            mul_mod_carry5_part1_suboffset: vec[231],
            mul_mod_carry5_part2_suboffset: vec[232],
            mul_mod_carry5_part3_suboffset: vec[233],
            mul_mod_carry5_part4_suboffset: vec[234],
            mul_mod_carry5_part5_suboffset: vec[235],
            mul_mod_carry5_part6_suboffset: vec[236],
            mul_mod_n_suboffset: vec[237],
            mul_mod_offsets_ptr_suboffset: vec[238],
            mul_mod_p0_suboffset: vec[239],
            mul_mod_p1_suboffset: vec[240],
            mul_mod_p2_suboffset: vec[241],
            mul_mod_p3_suboffset: vec[242],
            mul_mod_p_multiplier0_part0_suboffset: vec[243],
            mul_mod_p_multiplier0_part1_suboffset: vec[244],
            mul_mod_p_multiplier0_part2_suboffset: vec[245],
            mul_mod_p_multiplier0_part3_suboffset: vec[246],
            mul_mod_p_multiplier0_part4_suboffset: vec[247],
            mul_mod_p_multiplier0_part5_suboffset: vec[248],
            mul_mod_p_multiplier1_part0_suboffset: vec[249],
            mul_mod_p_multiplier1_part1_suboffset: vec[250],
            mul_mod_p_multiplier1_part2_suboffset: vec[251],
            mul_mod_p_multiplier1_part3_suboffset: vec[252],
            mul_mod_p_multiplier1_part4_suboffset: vec[253],
            mul_mod_p_multiplier1_part5_suboffset: vec[254],
            mul_mod_p_multiplier2_part0_suboffset: vec[255],
            mul_mod_p_multiplier2_part1_suboffset: vec[256],
            mul_mod_p_multiplier2_part2_suboffset: vec[257],
            mul_mod_p_multiplier2_part3_suboffset: vec[258],
            mul_mod_p_multiplier2_part4_suboffset: vec[259],
            mul_mod_p_multiplier2_part5_suboffset: vec[260],
            mul_mod_p_multiplier3_part0_suboffset: vec[261],
            mul_mod_p_multiplier3_part1_suboffset: vec[262],
            mul_mod_p_multiplier3_part2_suboffset: vec[263],
            mul_mod_p_multiplier3_part3_suboffset: vec[264],
            mul_mod_p_multiplier3_part4_suboffset: vec[265],
            mul_mod_p_multiplier3_part5_suboffset: vec[266],
            mul_mod_row_ratio: vec[267],
            mul_mod_values_ptr_suboffset: vec[268],
            num_columns_first: vec[269],
            num_columns_second: vec[270],
            orig_public_memory_suboffset: vec[271],
            pedersen_hash0_ec_subset_sum_bit_unpacking_prod_ones192_column: vec[272],
            pedersen_hash0_ec_subset_sum_bit_unpacking_prod_ones192_offset: vec[273],
            pedersen_hash0_ec_subset_sum_bit_unpacking_prod_ones196_column: vec[274],
            pedersen_hash0_ec_subset_sum_bit_unpacking_prod_ones196_offset: vec[275],
            pedersen_hash0_ec_subset_sum_partial_sum_x_column: vec[276],
            pedersen_hash0_ec_subset_sum_partial_sum_x_offset: vec[277],
            pedersen_hash0_ec_subset_sum_partial_sum_y_column: vec[278],
            pedersen_hash0_ec_subset_sum_partial_sum_y_offset: vec[279],
            pedersen_hash0_ec_subset_sum_selector_column: vec[280],
            pedersen_hash0_ec_subset_sum_selector_offset: vec[281],
            pedersen_hash0_ec_subset_sum_slope_column: vec[282],
            pedersen_hash0_ec_subset_sum_slope_offset: vec[283],
            pedersen_input0_suboffset: vec[284],
            pedersen_input1_suboffset: vec[285],
            pedersen_output_suboffset: vec[286],
            pedersen_builtin_row_ratio: vec[287],
            poseidon_param_0_input_output_suboffset: vec[288],
            poseidon_param_1_input_output_suboffset: vec[289],
            poseidon_param_2_input_output_suboffset: vec[290],
            poseidon_poseidon_full_rounds_state0_column: vec[291],
            poseidon_poseidon_full_rounds_state0_offset: vec[292],
            poseidon_poseidon_full_rounds_state0_squared_column: vec[293],
            poseidon_poseidon_full_rounds_state0_squared_offset: vec[294],
            poseidon_poseidon_full_rounds_state1_column: vec[295],
            poseidon_poseidon_full_rounds_state1_offset: vec[296],
            poseidon_poseidon_full_rounds_state1_squared_column: vec[297],
            poseidon_poseidon_full_rounds_state1_squared_offset: vec[298],
            poseidon_poseidon_full_rounds_state2_column: vec[299],
            poseidon_poseidon_full_rounds_state2_offset: vec[300],
            poseidon_poseidon_full_rounds_state2_squared_column: vec[301],
            poseidon_poseidon_full_rounds_state2_squared_offset: vec[302],
            poseidon_poseidon_partial_rounds_state0_column: vec[303],
            poseidon_poseidon_partial_rounds_state0_offset: vec[304],
            poseidon_poseidon_partial_rounds_state0_squared_column: vec[305],
            poseidon_poseidon_partial_rounds_state0_squared_offset: vec[306],
            poseidon_poseidon_partial_rounds_state1_column: vec[307],
            poseidon_poseidon_partial_rounds_state1_offset: vec[308],
            poseidon_poseidon_partial_rounds_state1_squared_column: vec[309],
            poseidon_poseidon_partial_rounds_state1_squared_offset: vec[310],
            poseidon_row_ratio: vec[311],
            range_check16_perm_cum_prod0_column: vec[312],
            range_check16_perm_cum_prod0_offset: vec[313],
            range_check16_sorted_column: vec[314],
            range_check16_sorted_offset: vec[315],
            range_check16_pool_column: vec[316],
            range_check16_pool_offset: vec[317],
            range_check96_builtin_inner_range_check0_suboffset: vec[318],
            range_check96_builtin_inner_range_check1_suboffset: vec[319],
            range_check96_builtin_inner_range_check2_suboffset: vec[320],
            range_check96_builtin_inner_range_check3_suboffset: vec[321],
            range_check96_builtin_inner_range_check4_suboffset: vec[322],
            range_check96_builtin_inner_range_check5_suboffset: vec[323],
            range_check96_builtin_mem_suboffset: vec[324],
            range_check96_builtin_row_ratio: vec[325],
            range_check_builtin_inner_range_check_suboffset: vec[326],
            range_check_builtin_mem_suboffset: vec[327],
            range_check_builtin_row_ratio: vec[328],
            range_check_units_row_ratio: vec[329],
            uses_add_mod_builtin: vec[330],
            uses_bitwise_builtin: vec[331],
            uses_ec_op_builtin: vec[332],
            uses_ecdsa_builtin: vec[333],
            uses_keccak_builtin: vec[334],
            uses_mul_mod_builtin: vec[335],
            uses_pedersen_builtin: vec[336],
            uses_poseidon_builtin: vec[337],
            uses_range_check96_builtin: vec[338],
            uses_range_check_builtin: vec[339],
        }
    }
}

use alloc::vec;

impl From<DynamicParams> for Vec<usize> {
    fn from(val: DynamicParams) -> Self {
        vec![
            val.add_mod_a0_suboffset,
            val.add_mod_a1_suboffset,
            val.add_mod_a2_suboffset,
            val.add_mod_a3_suboffset,
            val.add_mod_a_offset_suboffset,
            val.add_mod_b0_suboffset,
            val.add_mod_b1_suboffset,
            val.add_mod_b2_suboffset,
            val.add_mod_b3_suboffset,
            val.add_mod_b_offset_suboffset,
            val.add_mod_c0_suboffset,
            val.add_mod_c1_suboffset,
            val.add_mod_c2_suboffset,
            val.add_mod_c3_suboffset,
            val.add_mod_c_offset_suboffset,
            val.add_mod_carry1_bit_column,
            val.add_mod_carry1_bit_offset,
            val.add_mod_carry1_sign_column,
            val.add_mod_carry1_sign_offset,
            val.add_mod_carry2_bit_column,
            val.add_mod_carry2_bit_offset,
            val.add_mod_carry2_sign_column,
            val.add_mod_carry2_sign_offset,
            val.add_mod_carry3_bit_column,
            val.add_mod_carry3_bit_offset,
            val.add_mod_carry3_sign_column,
            val.add_mod_carry3_sign_offset,
            val.add_mod_n_suboffset,
            val.add_mod_offsets_ptr_suboffset,
            val.add_mod_p0_suboffset,
            val.add_mod_p1_suboffset,
            val.add_mod_p2_suboffset,
            val.add_mod_p3_suboffset,
            val.add_mod_row_ratio,
            val.add_mod_sub_p_bit_column,
            val.add_mod_sub_p_bit_offset,
            val.add_mod_values_ptr_suboffset,
            val.bitwise_diluted_var_pool_suboffset,
            val.bitwise_row_ratio,
            val.bitwise_trim_unpacking192_suboffset,
            val.bitwise_trim_unpacking193_suboffset,
            val.bitwise_trim_unpacking194_suboffset,
            val.bitwise_trim_unpacking195_suboffset,
            val.bitwise_var_pool_suboffset,
            val.bitwise_x_or_y_suboffset,
            val.cpu_decode_mem_inst_suboffset,
            val.cpu_decode_off0_suboffset,
            val.cpu_decode_off1_suboffset,
            val.cpu_decode_off2_suboffset,
            val.cpu_decode_opcode_range_check_column_column,
            val.cpu_decode_opcode_range_check_column_offset,
            val.cpu_operands_mem_dst_suboffset,
            val.cpu_operands_mem_op0_suboffset,
            val.cpu_operands_mem_op1_suboffset,
            val.cpu_operands_ops_mul_column,
            val.cpu_operands_ops_mul_offset,
            val.cpu_operands_res_column,
            val.cpu_operands_res_offset,
            val.cpu_registers_ap_column,
            val.cpu_registers_ap_offset,
            val.cpu_registers_fp_column,
            val.cpu_registers_fp_offset,
            val.cpu_update_registers_update_pc_tmp0_column,
            val.cpu_update_registers_update_pc_tmp0_offset,
            val.cpu_update_registers_update_pc_tmp1_column,
            val.cpu_update_registers_update_pc_tmp1_offset,
            val.cpu_component_step,
            val.diluted_check_cumulative_value_column,
            val.diluted_check_cumulative_value_offset,
            val.diluted_check_permutation_cum_prod0_column,
            val.diluted_check_permutation_cum_prod0_offset,
            val.diluted_check_permuted_values_column,
            val.diluted_check_permuted_values_offset,
            val.diluted_pool_column,
            val.diluted_pool_offset,
            val.diluted_units_row_ratio,
            val.ec_op_doubled_points_x_column,
            val.ec_op_doubled_points_x_offset,
            val.ec_op_doubled_points_y_column,
            val.ec_op_doubled_points_y_offset,
            val.ec_op_doubling_slope_column,
            val.ec_op_doubling_slope_offset,
            val.ec_op_ec_subset_sum_bit_unpacking_prod_ones192_column,
            val.ec_op_ec_subset_sum_bit_unpacking_prod_ones192_offset,
            val.ec_op_ec_subset_sum_bit_unpacking_prod_ones196_column,
            val.ec_op_ec_subset_sum_bit_unpacking_prod_ones196_offset,
            val.ec_op_ec_subset_sum_partial_sum_x_column,
            val.ec_op_ec_subset_sum_partial_sum_x_offset,
            val.ec_op_ec_subset_sum_partial_sum_y_column,
            val.ec_op_ec_subset_sum_partial_sum_y_offset,
            val.ec_op_ec_subset_sum_selector_column,
            val.ec_op_ec_subset_sum_selector_offset,
            val.ec_op_ec_subset_sum_slope_column,
            val.ec_op_ec_subset_sum_slope_offset,
            val.ec_op_ec_subset_sum_x_diff_inv_column,
            val.ec_op_ec_subset_sum_x_diff_inv_offset,
            val.ec_op_m_suboffset,
            val.ec_op_p_x_suboffset,
            val.ec_op_p_y_suboffset,
            val.ec_op_q_x_suboffset,
            val.ec_op_q_y_suboffset,
            val.ec_op_r_x_suboffset,
            val.ec_op_r_y_suboffset,
            val.ec_op_builtin_row_ratio,
            val.ecdsa_message_suboffset,
            val.ecdsa_pubkey_suboffset,
            val.ecdsa_signature0_add_results_inv_column,
            val.ecdsa_signature0_add_results_inv_offset,
            val.ecdsa_signature0_add_results_slope_column,
            val.ecdsa_signature0_add_results_slope_offset,
            val.ecdsa_signature0_doubling_slope_column,
            val.ecdsa_signature0_doubling_slope_offset,
            val.ecdsa_signature0_exponentiate_generator_partial_sum_x_column,
            val.ecdsa_signature0_exponentiate_generator_partial_sum_x_offset,
            val.ecdsa_signature0_exponentiate_generator_partial_sum_y_column,
            val.ecdsa_signature0_exponentiate_generator_partial_sum_y_offset,
            val.ecdsa_signature0_exponentiate_generator_selector_column,
            val.ecdsa_signature0_exponentiate_generator_selector_offset,
            val.ecdsa_signature0_exponentiate_generator_slope_column,
            val.ecdsa_signature0_exponentiate_generator_slope_offset,
            val.ecdsa_signature0_exponentiate_generator_x_diff_inv_column,
            val.ecdsa_signature0_exponentiate_generator_x_diff_inv_offset,
            val.ecdsa_signature0_exponentiate_key_partial_sum_x_column,
            val.ecdsa_signature0_exponentiate_key_partial_sum_x_offset,
            val.ecdsa_signature0_exponentiate_key_partial_sum_y_column,
            val.ecdsa_signature0_exponentiate_key_partial_sum_y_offset,
            val.ecdsa_signature0_exponentiate_key_selector_column,
            val.ecdsa_signature0_exponentiate_key_selector_offset,
            val.ecdsa_signature0_exponentiate_key_slope_column,
            val.ecdsa_signature0_exponentiate_key_slope_offset,
            val.ecdsa_signature0_exponentiate_key_x_diff_inv_column,
            val.ecdsa_signature0_exponentiate_key_x_diff_inv_offset,
            val.ecdsa_signature0_extract_r_inv_column,
            val.ecdsa_signature0_extract_r_inv_offset,
            val.ecdsa_signature0_extract_r_slope_column,
            val.ecdsa_signature0_extract_r_slope_offset,
            val.ecdsa_signature0_key_points_x_column,
            val.ecdsa_signature0_key_points_x_offset,
            val.ecdsa_signature0_key_points_y_column,
            val.ecdsa_signature0_key_points_y_offset,
            val.ecdsa_signature0_q_x_squared_column,
            val.ecdsa_signature0_q_x_squared_offset,
            val.ecdsa_signature0_r_w_inv_column,
            val.ecdsa_signature0_r_w_inv_offset,
            val.ecdsa_signature0_z_inv_column,
            val.ecdsa_signature0_z_inv_offset,
            val.ecdsa_builtin_row_ratio,
            val.keccak_input_output_suboffset,
            val.keccak_keccak_diluted_column0_suboffset,
            val.keccak_keccak_diluted_column1_suboffset,
            val.keccak_keccak_diluted_column2_suboffset,
            val.keccak_keccak_diluted_column3_suboffset,
            val.keccak_keccak_parse_to_diluted_cumulative_sum_column,
            val.keccak_keccak_parse_to_diluted_cumulative_sum_offset,
            val.keccak_keccak_parse_to_diluted_final_reshaped_input_column,
            val.keccak_keccak_parse_to_diluted_final_reshaped_input_offset,
            val.keccak_keccak_parse_to_diluted_reshaped_intermediate_column,
            val.keccak_keccak_parse_to_diluted_reshaped_intermediate_offset,
            val.keccak_keccak_rotated_parity0_column,
            val.keccak_keccak_rotated_parity0_offset,
            val.keccak_keccak_rotated_parity1_column,
            val.keccak_keccak_rotated_parity1_offset,
            val.keccak_keccak_rotated_parity2_column,
            val.keccak_keccak_rotated_parity2_offset,
            val.keccak_keccak_rotated_parity3_column,
            val.keccak_keccak_rotated_parity3_offset,
            val.keccak_keccak_rotated_parity4_column,
            val.keccak_keccak_rotated_parity4_offset,
            val.keccak_row_ratio,
            val.mem_pool_addr_column,
            val.mem_pool_addr_offset,
            val.mem_pool_value_column,
            val.mem_pool_value_offset,
            val.memory_multi_column_perm_perm_cum_prod0_column,
            val.memory_multi_column_perm_perm_cum_prod0_offset,
            val.memory_sorted_addr_column,
            val.memory_sorted_addr_offset,
            val.memory_sorted_value_column,
            val.memory_sorted_value_offset,
            val.memory_units_row_ratio,
            val.mul_mod_a0_suboffset,
            val.mul_mod_a1_suboffset,
            val.mul_mod_a2_suboffset,
            val.mul_mod_a3_suboffset,
            val.mul_mod_a_offset_suboffset,
            val.mul_mod_b0_suboffset,
            val.mul_mod_b1_suboffset,
            val.mul_mod_b2_suboffset,
            val.mul_mod_b3_suboffset,
            val.mul_mod_b_offset_suboffset,
            val.mul_mod_c0_suboffset,
            val.mul_mod_c1_suboffset,
            val.mul_mod_c2_suboffset,
            val.mul_mod_c3_suboffset,
            val.mul_mod_c_offset_suboffset,
            val.mul_mod_carry0_part0_suboffset,
            val.mul_mod_carry0_part1_suboffset,
            val.mul_mod_carry0_part2_suboffset,
            val.mul_mod_carry0_part3_suboffset,
            val.mul_mod_carry0_part4_suboffset,
            val.mul_mod_carry0_part5_suboffset,
            val.mul_mod_carry0_part6_suboffset,
            val.mul_mod_carry1_part0_suboffset,
            val.mul_mod_carry1_part1_suboffset,
            val.mul_mod_carry1_part2_suboffset,
            val.mul_mod_carry1_part3_suboffset,
            val.mul_mod_carry1_part4_suboffset,
            val.mul_mod_carry1_part5_suboffset,
            val.mul_mod_carry1_part6_suboffset,
            val.mul_mod_carry2_part0_suboffset,
            val.mul_mod_carry2_part1_suboffset,
            val.mul_mod_carry2_part2_suboffset,
            val.mul_mod_carry2_part3_suboffset,
            val.mul_mod_carry2_part4_suboffset,
            val.mul_mod_carry2_part5_suboffset,
            val.mul_mod_carry2_part6_suboffset,
            val.mul_mod_carry3_part0_suboffset,
            val.mul_mod_carry3_part1_suboffset,
            val.mul_mod_carry3_part2_suboffset,
            val.mul_mod_carry3_part3_suboffset,
            val.mul_mod_carry3_part4_suboffset,
            val.mul_mod_carry3_part5_suboffset,
            val.mul_mod_carry3_part6_suboffset,
            val.mul_mod_carry4_part0_suboffset,
            val.mul_mod_carry4_part1_suboffset,
            val.mul_mod_carry4_part2_suboffset,
            val.mul_mod_carry4_part3_suboffset,
            val.mul_mod_carry4_part4_suboffset,
            val.mul_mod_carry4_part5_suboffset,
            val.mul_mod_carry4_part6_suboffset,
            val.mul_mod_carry5_part0_suboffset,
            val.mul_mod_carry5_part1_suboffset,
            val.mul_mod_carry5_part2_suboffset,
            val.mul_mod_carry5_part3_suboffset,
            val.mul_mod_carry5_part4_suboffset,
            val.mul_mod_carry5_part5_suboffset,
            val.mul_mod_carry5_part6_suboffset,
            val.mul_mod_n_suboffset,
            val.mul_mod_offsets_ptr_suboffset,
            val.mul_mod_p0_suboffset,
            val.mul_mod_p1_suboffset,
            val.mul_mod_p2_suboffset,
            val.mul_mod_p3_suboffset,
            val.mul_mod_p_multiplier0_part0_suboffset,
            val.mul_mod_p_multiplier0_part1_suboffset,
            val.mul_mod_p_multiplier0_part2_suboffset,
            val.mul_mod_p_multiplier0_part3_suboffset,
            val.mul_mod_p_multiplier0_part4_suboffset,
            val.mul_mod_p_multiplier0_part5_suboffset,
            val.mul_mod_p_multiplier1_part0_suboffset,
            val.mul_mod_p_multiplier1_part1_suboffset,
            val.mul_mod_p_multiplier1_part2_suboffset,
            val.mul_mod_p_multiplier1_part3_suboffset,
            val.mul_mod_p_multiplier1_part4_suboffset,
            val.mul_mod_p_multiplier1_part5_suboffset,
            val.mul_mod_p_multiplier2_part0_suboffset,
            val.mul_mod_p_multiplier2_part1_suboffset,
            val.mul_mod_p_multiplier2_part2_suboffset,
            val.mul_mod_p_multiplier2_part3_suboffset,
            val.mul_mod_p_multiplier2_part4_suboffset,
            val.mul_mod_p_multiplier2_part5_suboffset,
            val.mul_mod_p_multiplier3_part0_suboffset,
            val.mul_mod_p_multiplier3_part1_suboffset,
            val.mul_mod_p_multiplier3_part2_suboffset,
            val.mul_mod_p_multiplier3_part3_suboffset,
            val.mul_mod_p_multiplier3_part4_suboffset,
            val.mul_mod_p_multiplier3_part5_suboffset,
            val.mul_mod_row_ratio,
            val.mul_mod_values_ptr_suboffset,
            val.num_columns_first,
            val.num_columns_second,
            val.orig_public_memory_suboffset,
            val.pedersen_hash0_ec_subset_sum_bit_unpacking_prod_ones192_column,
            val.pedersen_hash0_ec_subset_sum_bit_unpacking_prod_ones192_offset,
            val.pedersen_hash0_ec_subset_sum_bit_unpacking_prod_ones196_column,
            val.pedersen_hash0_ec_subset_sum_bit_unpacking_prod_ones196_offset,
            val.pedersen_hash0_ec_subset_sum_partial_sum_x_column,
            val.pedersen_hash0_ec_subset_sum_partial_sum_x_offset,
            val.pedersen_hash0_ec_subset_sum_partial_sum_y_column,
            val.pedersen_hash0_ec_subset_sum_partial_sum_y_offset,
            val.pedersen_hash0_ec_subset_sum_selector_column,
            val.pedersen_hash0_ec_subset_sum_selector_offset,
            val.pedersen_hash0_ec_subset_sum_slope_column,
            val.pedersen_hash0_ec_subset_sum_slope_offset,
            val.pedersen_input0_suboffset,
            val.pedersen_input1_suboffset,
            val.pedersen_output_suboffset,
            val.pedersen_builtin_row_ratio,
            val.poseidon_param_0_input_output_suboffset,
            val.poseidon_param_1_input_output_suboffset,
            val.poseidon_param_2_input_output_suboffset,
            val.poseidon_poseidon_full_rounds_state0_column,
            val.poseidon_poseidon_full_rounds_state0_offset,
            val.poseidon_poseidon_full_rounds_state0_squared_column,
            val.poseidon_poseidon_full_rounds_state0_squared_offset,
            val.poseidon_poseidon_full_rounds_state1_column,
            val.poseidon_poseidon_full_rounds_state1_offset,
            val.poseidon_poseidon_full_rounds_state1_squared_column,
            val.poseidon_poseidon_full_rounds_state1_squared_offset,
            val.poseidon_poseidon_full_rounds_state2_column,
            val.poseidon_poseidon_full_rounds_state2_offset,
            val.poseidon_poseidon_full_rounds_state2_squared_column,
            val.poseidon_poseidon_full_rounds_state2_squared_offset,
            val.poseidon_poseidon_partial_rounds_state0_column,
            val.poseidon_poseidon_partial_rounds_state0_offset,
            val.poseidon_poseidon_partial_rounds_state0_squared_column,
            val.poseidon_poseidon_partial_rounds_state0_squared_offset,
            val.poseidon_poseidon_partial_rounds_state1_column,
            val.poseidon_poseidon_partial_rounds_state1_offset,
            val.poseidon_poseidon_partial_rounds_state1_squared_column,
            val.poseidon_poseidon_partial_rounds_state1_squared_offset,
            val.poseidon_row_ratio,
            val.range_check16_perm_cum_prod0_column,
            val.range_check16_perm_cum_prod0_offset,
            val.range_check16_sorted_column,
            val.range_check16_sorted_offset,
            val.range_check16_pool_column,
            val.range_check16_pool_offset,
            val.range_check96_builtin_inner_range_check0_suboffset,
            val.range_check96_builtin_inner_range_check1_suboffset,
            val.range_check96_builtin_inner_range_check2_suboffset,
            val.range_check96_builtin_inner_range_check3_suboffset,
            val.range_check96_builtin_inner_range_check4_suboffset,
            val.range_check96_builtin_inner_range_check5_suboffset,
            val.range_check96_builtin_mem_suboffset,
            val.range_check96_builtin_row_ratio,
            val.range_check_builtin_inner_range_check_suboffset,
            val.range_check_builtin_mem_suboffset,
            val.range_check_builtin_row_ratio,
            val.range_check_units_row_ratio,
            val.uses_add_mod_builtin,
            val.uses_bitwise_builtin,
            val.uses_ec_op_builtin,
            val.uses_ecdsa_builtin,
            val.uses_keccak_builtin,
            val.uses_mul_mod_builtin,
            val.uses_pedersen_builtin,
            val.uses_poseidon_builtin,
            val.uses_range_check96_builtin,
            val.uses_range_check_builtin,
        ]
    }
}
