use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DynamicParams {
    pub add_mod_a0_suboffset: usize,
    pub add_mod_a1_suboffset: usize,
    pub add_mod_a2_suboffset: usize,
    pub add_mod_a3_suboffset: usize,
    pub add_mod_a_offset_suboffset: usize,
    pub add_mod_b0_suboffset: usize,
    pub add_mod_b1_suboffset: usize,
    pub add_mod_b2_suboffset: usize,
    pub add_mod_b3_suboffset: usize,
    pub add_mod_b_offset_suboffset: usize,
    pub add_mod_c0_suboffset: usize,
    pub add_mod_c1_suboffset: usize,
    pub add_mod_c2_suboffset: usize,
    pub add_mod_c3_suboffset: usize,
    pub add_mod_c_offset_suboffset: usize,
    pub add_mod_carry1_bit_column: usize,
    pub add_mod_carry1_bit_offset: usize,
    pub add_mod_carry1_sign_column: usize,
    pub add_mod_carry1_sign_offset: usize,
    pub add_mod_carry2_bit_column: usize,
    pub add_mod_carry2_bit_offset: usize,
    pub add_mod_carry2_sign_column: usize,
    pub add_mod_carry2_sign_offset: usize,
    pub add_mod_carry3_bit_column: usize,
    pub add_mod_carry3_bit_offset: usize,
    pub add_mod_carry3_sign_column: usize,
    pub add_mod_carry3_sign_offset: usize,
    pub add_mod_n_suboffset: usize,
    pub add_mod_offsets_ptr_suboffset: usize,
    pub add_mod_p0_suboffset: usize,
    pub add_mod_p1_suboffset: usize,
    pub add_mod_p2_suboffset: usize,
    pub add_mod_p3_suboffset: usize,
    pub add_mod_row_ratio: usize,
    pub add_mod_sub_p_bit_column: usize,
    pub add_mod_sub_p_bit_offset: usize,
    pub add_mod_values_ptr_suboffset: usize,
    pub bitwise_diluted_var_pool_suboffset: usize,
    pub bitwise_row_ratio: usize,
    pub bitwise_trim_unpacking192_suboffset: usize,
    pub bitwise_trim_unpacking193_suboffset: usize,
    pub bitwise_trim_unpacking194_suboffset: usize,
    pub bitwise_trim_unpacking195_suboffset: usize,
    pub bitwise_var_pool_suboffset: usize,
    pub bitwise_x_or_y_suboffset: usize,
    pub cpu_decode_mem_inst_suboffset: usize,
    pub cpu_decode_off0_suboffset: usize,
    pub cpu_decode_off1_suboffset: usize,
    pub cpu_decode_off2_suboffset: usize,
    pub cpu_decode_opcode_range_check_column_column: usize,
    pub cpu_decode_opcode_range_check_column_offset: usize,
    pub cpu_operands_mem_dst_suboffset: usize,
    pub cpu_operands_mem_op0_suboffset: usize,
    pub cpu_operands_mem_op1_suboffset: usize,
    pub cpu_operands_ops_mul_column: usize,
    pub cpu_operands_ops_mul_offset: usize,
    pub cpu_operands_res_column: usize,
    pub cpu_operands_res_offset: usize,
    pub cpu_registers_ap_column: usize,
    pub cpu_registers_ap_offset: usize,
    pub cpu_registers_fp_column: usize,
    pub cpu_registers_fp_offset: usize,
    pub cpu_update_registers_update_pc_tmp0_column: usize,
    pub cpu_update_registers_update_pc_tmp0_offset: usize,
    pub cpu_update_registers_update_pc_tmp1_column: usize,
    pub cpu_update_registers_update_pc_tmp1_offset: usize,
    pub cpu_component_step: usize,
    pub diluted_check_cumulative_value_column: usize,
    pub diluted_check_cumulative_value_offset: usize,
    pub diluted_check_permutation_cum_prod0_column: usize,
    pub diluted_check_permutation_cum_prod0_offset: usize,
    pub diluted_check_permuted_values_column: usize,
    pub diluted_check_permuted_values_offset: usize,
    pub diluted_pool_column: usize,
    pub diluted_pool_offset: usize,
    pub diluted_units_row_ratio: usize,
    pub ec_op_doubled_points_x_column: usize,
    pub ec_op_doubled_points_x_offset: usize,
    pub ec_op_doubled_points_y_column: usize,
    pub ec_op_doubled_points_y_offset: usize,
    pub ec_op_doubling_slope_column: usize,
    pub ec_op_doubling_slope_offset: usize,
    pub ec_op_ec_subset_sum_bit_unpacking_prod_ones192_column: usize,
    pub ec_op_ec_subset_sum_bit_unpacking_prod_ones192_offset: usize,
    pub ec_op_ec_subset_sum_bit_unpacking_prod_ones196_column: usize,
    pub ec_op_ec_subset_sum_bit_unpacking_prod_ones196_offset: usize,
    pub ec_op_ec_subset_sum_partial_sum_x_column: usize,
    pub ec_op_ec_subset_sum_partial_sum_x_offset: usize,
    pub ec_op_ec_subset_sum_partial_sum_y_column: usize,
    pub ec_op_ec_subset_sum_partial_sum_y_offset: usize,
    pub ec_op_ec_subset_sum_selector_column: usize,
    pub ec_op_ec_subset_sum_selector_offset: usize,
    pub ec_op_ec_subset_sum_slope_column: usize,
    pub ec_op_ec_subset_sum_slope_offset: usize,
    pub ec_op_ec_subset_sum_x_diff_inv_column: usize,
    pub ec_op_ec_subset_sum_x_diff_inv_offset: usize,
    pub ec_op_m_suboffset: usize,
    pub ec_op_p_x_suboffset: usize,
    pub ec_op_p_y_suboffset: usize,
    pub ec_op_q_x_suboffset: usize,
    pub ec_op_q_y_suboffset: usize,
    pub ec_op_r_x_suboffset: usize,
    pub ec_op_r_y_suboffset: usize,
    pub ec_op_builtin_row_ratio: usize,
    pub ecdsa_message_suboffset: usize,
    pub ecdsa_pubkey_suboffset: usize,
    pub ecdsa_signature0_add_results_inv_column: usize,
    pub ecdsa_signature0_add_results_inv_offset: usize,
    pub ecdsa_signature0_add_results_slope_column: usize,
    pub ecdsa_signature0_add_results_slope_offset: usize,
    pub ecdsa_signature0_doubling_slope_column: usize,
    pub ecdsa_signature0_doubling_slope_offset: usize,
    pub ecdsa_signature0_exponentiate_generator_partial_sum_x_column: usize,
    pub ecdsa_signature0_exponentiate_generator_partial_sum_x_offset: usize,
    pub ecdsa_signature0_exponentiate_generator_partial_sum_y_column: usize,
    pub ecdsa_signature0_exponentiate_generator_partial_sum_y_offset: usize,
    pub ecdsa_signature0_exponentiate_generator_selector_column: usize,
    pub ecdsa_signature0_exponentiate_generator_selector_offset: usize,
    pub ecdsa_signature0_exponentiate_generator_slope_column: usize,
    pub ecdsa_signature0_exponentiate_generator_slope_offset: usize,
    pub ecdsa_signature0_exponentiate_generator_x_diff_inv_column: usize,
    pub ecdsa_signature0_exponentiate_generator_x_diff_inv_offset: usize,
    pub ecdsa_signature0_exponentiate_key_partial_sum_x_column: usize,
    pub ecdsa_signature0_exponentiate_key_partial_sum_x_offset: usize,
    pub ecdsa_signature0_exponentiate_key_partial_sum_y_column: usize,
    pub ecdsa_signature0_exponentiate_key_partial_sum_y_offset: usize,
    pub ecdsa_signature0_exponentiate_key_selector_column: usize,
    pub ecdsa_signature0_exponentiate_key_selector_offset: usize,
    pub ecdsa_signature0_exponentiate_key_slope_column: usize,
    pub ecdsa_signature0_exponentiate_key_slope_offset: usize,
    pub ecdsa_signature0_exponentiate_key_x_diff_inv_column: usize,
    pub ecdsa_signature0_exponentiate_key_x_diff_inv_offset: usize,
    pub ecdsa_signature0_extract_r_inv_column: usize,
    pub ecdsa_signature0_extract_r_inv_offset: usize,
    pub ecdsa_signature0_extract_r_slope_column: usize,
    pub ecdsa_signature0_extract_r_slope_offset: usize,
    pub ecdsa_signature0_key_points_x_column: usize,
    pub ecdsa_signature0_key_points_x_offset: usize,
    pub ecdsa_signature0_key_points_y_column: usize,
    pub ecdsa_signature0_key_points_y_offset: usize,
    pub ecdsa_signature0_q_x_squared_column: usize,
    pub ecdsa_signature0_q_x_squared_offset: usize,
    pub ecdsa_signature0_r_w_inv_column: usize,
    pub ecdsa_signature0_r_w_inv_offset: usize,
    pub ecdsa_signature0_z_inv_column: usize,
    pub ecdsa_signature0_z_inv_offset: usize,
    pub ecdsa_builtin_row_ratio: usize,
    pub keccak_input_output_suboffset: usize,
    pub keccak_keccak_diluted_column0_suboffset: usize,
    pub keccak_keccak_diluted_column1_suboffset: usize,
    pub keccak_keccak_diluted_column2_suboffset: usize,
    pub keccak_keccak_diluted_column3_suboffset: usize,
    pub keccak_keccak_parse_to_diluted_cumulative_sum_column: usize,
    pub keccak_keccak_parse_to_diluted_cumulative_sum_offset: usize,
    pub keccak_keccak_parse_to_diluted_final_reshaped_input_column: usize,
    pub keccak_keccak_parse_to_diluted_final_reshaped_input_offset: usize,
    pub keccak_keccak_parse_to_diluted_reshaped_intermediate_column: usize,
    pub keccak_keccak_parse_to_diluted_reshaped_intermediate_offset: usize,
    pub keccak_keccak_rotated_parity0_column: usize,
    pub keccak_keccak_rotated_parity0_offset: usize,
    pub keccak_keccak_rotated_parity1_column: usize,
    pub keccak_keccak_rotated_parity1_offset: usize,
    pub keccak_keccak_rotated_parity2_column: usize,
    pub keccak_keccak_rotated_parity2_offset: usize,
    pub keccak_keccak_rotated_parity3_column: usize,
    pub keccak_keccak_rotated_parity3_offset: usize,
    pub keccak_keccak_rotated_parity4_column: usize,
    pub keccak_keccak_rotated_parity4_offset: usize,
    pub keccak_row_ratio: usize,
    pub mem_pool_addr_column: usize,
    pub mem_pool_addr_offset: usize,
    pub mem_pool_value_column: usize,
    pub mem_pool_value_offset: usize,
    pub memory_multi_column_perm_perm_cum_prod0_column: usize,
    pub memory_multi_column_perm_perm_cum_prod0_offset: usize,
    pub memory_sorted_addr_column: usize,
    pub memory_sorted_addr_offset: usize,
    pub memory_sorted_value_column: usize,
    pub memory_sorted_value_offset: usize,
    pub memory_units_row_ratio: usize,
    pub mul_mod_a0_suboffset: usize,
    pub mul_mod_a1_suboffset: usize,
    pub mul_mod_a2_suboffset: usize,
    pub mul_mod_a3_suboffset: usize,
    pub mul_mod_a_offset_suboffset: usize,
    pub mul_mod_b0_suboffset: usize,
    pub mul_mod_b1_suboffset: usize,
    pub mul_mod_b2_suboffset: usize,
    pub mul_mod_b3_suboffset: usize,
    pub mul_mod_b_offset_suboffset: usize,
    pub mul_mod_c0_suboffset: usize,
    pub mul_mod_c1_suboffset: usize,
    pub mul_mod_c2_suboffset: usize,
    pub mul_mod_c3_suboffset: usize,
    pub mul_mod_c_offset_suboffset: usize,
    pub mul_mod_carry0_part0_suboffset: usize,
    pub mul_mod_carry0_part1_suboffset: usize,
    pub mul_mod_carry0_part2_suboffset: usize,
    pub mul_mod_carry0_part3_suboffset: usize,
    pub mul_mod_carry0_part4_suboffset: usize,
    pub mul_mod_carry0_part5_suboffset: usize,
    pub mul_mod_carry0_part6_suboffset: usize,
    pub mul_mod_carry1_part0_suboffset: usize,
    pub mul_mod_carry1_part1_suboffset: usize,
    pub mul_mod_carry1_part2_suboffset: usize,
    pub mul_mod_carry1_part3_suboffset: usize,
    pub mul_mod_carry1_part4_suboffset: usize,
    pub mul_mod_carry1_part5_suboffset: usize,
    pub mul_mod_carry1_part6_suboffset: usize,
    pub mul_mod_carry2_part0_suboffset: usize,
    pub mul_mod_carry2_part1_suboffset: usize,
    pub mul_mod_carry2_part2_suboffset: usize,
    pub mul_mod_carry2_part3_suboffset: usize,
    pub mul_mod_carry2_part4_suboffset: usize,
    pub mul_mod_carry2_part5_suboffset: usize,
    pub mul_mod_carry2_part6_suboffset: usize,
    pub mul_mod_carry3_part0_suboffset: usize,
    pub mul_mod_carry3_part1_suboffset: usize,
    pub mul_mod_carry3_part2_suboffset: usize,
    pub mul_mod_carry3_part3_suboffset: usize,
    pub mul_mod_carry3_part4_suboffset: usize,
    pub mul_mod_carry3_part5_suboffset: usize,
    pub mul_mod_carry3_part6_suboffset: usize,
    pub mul_mod_carry4_part0_suboffset: usize,
    pub mul_mod_carry4_part1_suboffset: usize,
    pub mul_mod_carry4_part2_suboffset: usize,
    pub mul_mod_carry4_part3_suboffset: usize,
    pub mul_mod_carry4_part4_suboffset: usize,
    pub mul_mod_carry4_part5_suboffset: usize,
    pub mul_mod_carry4_part6_suboffset: usize,
    pub mul_mod_carry5_part0_suboffset: usize,
    pub mul_mod_carry5_part1_suboffset: usize,
    pub mul_mod_carry5_part2_suboffset: usize,
    pub mul_mod_carry5_part3_suboffset: usize,
    pub mul_mod_carry5_part4_suboffset: usize,
    pub mul_mod_carry5_part5_suboffset: usize,
    pub mul_mod_carry5_part6_suboffset: usize,
    pub mul_mod_n_suboffset: usize,
    pub mul_mod_offsets_ptr_suboffset: usize,
    pub mul_mod_p0_suboffset: usize,
    pub mul_mod_p1_suboffset: usize,
    pub mul_mod_p2_suboffset: usize,
    pub mul_mod_p3_suboffset: usize,
    pub mul_mod_p_multiplier0_part0_suboffset: usize,
    pub mul_mod_p_multiplier0_part1_suboffset: usize,
    pub mul_mod_p_multiplier0_part2_suboffset: usize,
    pub mul_mod_p_multiplier0_part3_suboffset: usize,
    pub mul_mod_p_multiplier0_part4_suboffset: usize,
    pub mul_mod_p_multiplier0_part5_suboffset: usize,
    pub mul_mod_p_multiplier1_part0_suboffset: usize,
    pub mul_mod_p_multiplier1_part1_suboffset: usize,
    pub mul_mod_p_multiplier1_part2_suboffset: usize,
    pub mul_mod_p_multiplier1_part3_suboffset: usize,
    pub mul_mod_p_multiplier1_part4_suboffset: usize,
    pub mul_mod_p_multiplier1_part5_suboffset: usize,
    pub mul_mod_p_multiplier2_part0_suboffset: usize,
    pub mul_mod_p_multiplier2_part1_suboffset: usize,
    pub mul_mod_p_multiplier2_part2_suboffset: usize,
    pub mul_mod_p_multiplier2_part3_suboffset: usize,
    pub mul_mod_p_multiplier2_part4_suboffset: usize,
    pub mul_mod_p_multiplier2_part5_suboffset: usize,
    pub mul_mod_p_multiplier3_part0_suboffset: usize,
    pub mul_mod_p_multiplier3_part1_suboffset: usize,
    pub mul_mod_p_multiplier3_part2_suboffset: usize,
    pub mul_mod_p_multiplier3_part3_suboffset: usize,
    pub mul_mod_p_multiplier3_part4_suboffset: usize,
    pub mul_mod_p_multiplier3_part5_suboffset: usize,
    pub mul_mod_row_ratio: usize,
    pub mul_mod_values_ptr_suboffset: usize,
    pub num_columns_first: usize,
    pub num_columns_second: usize,
    pub orig_public_memory_suboffset: usize,
    pub pedersen_hash0_ec_subset_sum_bit_unpacking_prod_ones192_column: usize,
    pub pedersen_hash0_ec_subset_sum_bit_unpacking_prod_ones192_offset: usize,
    pub pedersen_hash0_ec_subset_sum_bit_unpacking_prod_ones196_column: usize,
    pub pedersen_hash0_ec_subset_sum_bit_unpacking_prod_ones196_offset: usize,
    pub pedersen_hash0_ec_subset_sum_partial_sum_x_column: usize,
    pub pedersen_hash0_ec_subset_sum_partial_sum_x_offset: usize,
    pub pedersen_hash0_ec_subset_sum_partial_sum_y_column: usize,
    pub pedersen_hash0_ec_subset_sum_partial_sum_y_offset: usize,
    pub pedersen_hash0_ec_subset_sum_selector_column: usize,
    pub pedersen_hash0_ec_subset_sum_selector_offset: usize,
    pub pedersen_hash0_ec_subset_sum_slope_column: usize,
    pub pedersen_hash0_ec_subset_sum_slope_offset: usize,
    pub pedersen_input0_suboffset: usize,
    pub pedersen_input1_suboffset: usize,
    pub pedersen_output_suboffset: usize,
    pub pedersen_builtin_row_ratio: usize,
    pub poseidon_param_0_input_output_suboffset: usize,
    pub poseidon_param_1_input_output_suboffset: usize,
    pub poseidon_param_2_input_output_suboffset: usize,
    pub poseidon_poseidon_full_rounds_state0_column: usize,
    pub poseidon_poseidon_full_rounds_state0_offset: usize,
    pub poseidon_poseidon_full_rounds_state0_squared_column: usize,
    pub poseidon_poseidon_full_rounds_state0_squared_offset: usize,
    pub poseidon_poseidon_full_rounds_state1_column: usize,
    pub poseidon_poseidon_full_rounds_state1_offset: usize,
    pub poseidon_poseidon_full_rounds_state1_squared_column: usize,
    pub poseidon_poseidon_full_rounds_state1_squared_offset: usize,
    pub poseidon_poseidon_full_rounds_state2_column: usize,
    pub poseidon_poseidon_full_rounds_state2_offset: usize,
    pub poseidon_poseidon_full_rounds_state2_squared_column: usize,
    pub poseidon_poseidon_full_rounds_state2_squared_offset: usize,
    pub poseidon_poseidon_partial_rounds_state0_column: usize,
    pub poseidon_poseidon_partial_rounds_state0_offset: usize,
    pub poseidon_poseidon_partial_rounds_state0_squared_column: usize,
    pub poseidon_poseidon_partial_rounds_state0_squared_offset: usize,
    pub poseidon_poseidon_partial_rounds_state1_column: usize,
    pub poseidon_poseidon_partial_rounds_state1_offset: usize,
    pub poseidon_poseidon_partial_rounds_state1_squared_column: usize,
    pub poseidon_poseidon_partial_rounds_state1_squared_offset: usize,
    pub poseidon_row_ratio: usize,
    pub range_check16_perm_cum_prod0_column: usize,
    pub range_check16_perm_cum_prod0_offset: usize,
    pub range_check16_sorted_column: usize,
    pub range_check16_sorted_offset: usize,
    pub range_check16_pool_column: usize,
    pub range_check16_pool_offset: usize,
    pub range_check96_builtin_inner_range_check0_suboffset: usize,
    pub range_check96_builtin_inner_range_check1_suboffset: usize,
    pub range_check96_builtin_inner_range_check2_suboffset: usize,
    pub range_check96_builtin_inner_range_check3_suboffset: usize,
    pub range_check96_builtin_inner_range_check4_suboffset: usize,
    pub range_check96_builtin_inner_range_check5_suboffset: usize,
    pub range_check96_builtin_mem_suboffset: usize,
    pub range_check96_builtin_row_ratio: usize,
    pub range_check_builtin_inner_range_check_suboffset: usize,
    pub range_check_builtin_mem_suboffset: usize,
    pub range_check_builtin_row_ratio: usize,
    pub range_check_units_row_ratio: usize,
    pub uses_add_mod_builtin: usize,
    pub uses_bitwise_builtin: usize,
    pub uses_ec_op_builtin: usize,
    pub uses_ecdsa_builtin: usize,
    pub uses_keccak_builtin: usize,
    pub uses_mul_mod_builtin: usize,
    pub uses_pedersen_builtin: usize,
    pub uses_poseidon_builtin: usize,
    pub uses_range_check96_builtin: usize,
    pub uses_range_check_builtin: usize,
}

use alloc::vec;

impl IntoIterator for DynamicParams {
    type Item = usize;
    type IntoIter = vec::IntoIter<Self::Item>;
    fn into_iter(self) -> Self::IntoIter {
        vec![
            self.add_mod_a0_suboffset,
            self.add_mod_a1_suboffset,
            self.add_mod_a2_suboffset,
            self.add_mod_a3_suboffset,
            self.add_mod_a_offset_suboffset,
            self.add_mod_b0_suboffset,
            self.add_mod_b1_suboffset,
            self.add_mod_b2_suboffset,
            self.add_mod_b3_suboffset,
            self.add_mod_b_offset_suboffset,
            self.add_mod_c0_suboffset,
            self.add_mod_c1_suboffset,
            self.add_mod_c2_suboffset,
            self.add_mod_c3_suboffset,
            self.add_mod_c_offset_suboffset,
            self.add_mod_carry1_bit_column,
            self.add_mod_carry1_bit_offset,
            self.add_mod_carry1_sign_column,
            self.add_mod_carry1_sign_offset,
            self.add_mod_carry2_bit_column,
            self.add_mod_carry2_bit_offset,
            self.add_mod_carry2_sign_column,
            self.add_mod_carry2_sign_offset,
            self.add_mod_carry3_bit_column,
            self.add_mod_carry3_bit_offset,
            self.add_mod_carry3_sign_column,
            self.add_mod_carry3_sign_offset,
            self.add_mod_n_suboffset,
            self.add_mod_offsets_ptr_suboffset,
            self.add_mod_p0_suboffset,
            self.add_mod_p1_suboffset,
            self.add_mod_p2_suboffset,
            self.add_mod_p3_suboffset,
            self.add_mod_row_ratio,
            self.add_mod_sub_p_bit_column,
            self.add_mod_sub_p_bit_offset,
            self.add_mod_values_ptr_suboffset,
            self.bitwise_diluted_var_pool_suboffset,
            self.bitwise_row_ratio,
            self.bitwise_trim_unpacking192_suboffset,
            self.bitwise_trim_unpacking193_suboffset,
            self.bitwise_trim_unpacking194_suboffset,
            self.bitwise_trim_unpacking195_suboffset,
            self.bitwise_var_pool_suboffset,
            self.bitwise_x_or_y_suboffset,
            self.cpu_decode_mem_inst_suboffset,
            self.cpu_decode_off0_suboffset,
            self.cpu_decode_off1_suboffset,
            self.cpu_decode_off2_suboffset,
            self.cpu_decode_opcode_range_check_column_column,
            self.cpu_decode_opcode_range_check_column_offset,
            self.cpu_operands_mem_dst_suboffset,
            self.cpu_operands_mem_op0_suboffset,
            self.cpu_operands_mem_op1_suboffset,
            self.cpu_operands_ops_mul_column,
            self.cpu_operands_ops_mul_offset,
            self.cpu_operands_res_column,
            self.cpu_operands_res_offset,
            self.cpu_registers_ap_column,
            self.cpu_registers_ap_offset,
            self.cpu_registers_fp_column,
            self.cpu_registers_fp_offset,
            self.cpu_update_registers_update_pc_tmp0_column,
            self.cpu_update_registers_update_pc_tmp0_offset,
            self.cpu_update_registers_update_pc_tmp1_column,
            self.cpu_update_registers_update_pc_tmp1_offset,
            self.cpu_component_step,
            self.diluted_check_cumulative_value_column,
            self.diluted_check_cumulative_value_offset,
            self.diluted_check_permutation_cum_prod0_column,
            self.diluted_check_permutation_cum_prod0_offset,
            self.diluted_check_permuted_values_column,
            self.diluted_check_permuted_values_offset,
            self.diluted_pool_column,
            self.diluted_pool_offset,
            self.diluted_units_row_ratio,
            self.ec_op_doubled_points_x_column,
            self.ec_op_doubled_points_x_offset,
            self.ec_op_doubled_points_y_column,
            self.ec_op_doubled_points_y_offset,
            self.ec_op_doubling_slope_column,
            self.ec_op_doubling_slope_offset,
            self.ec_op_ec_subset_sum_bit_unpacking_prod_ones192_column,
            self.ec_op_ec_subset_sum_bit_unpacking_prod_ones192_offset,
            self.ec_op_ec_subset_sum_bit_unpacking_prod_ones196_column,
            self.ec_op_ec_subset_sum_bit_unpacking_prod_ones196_offset,
            self.ec_op_ec_subset_sum_partial_sum_x_column,
            self.ec_op_ec_subset_sum_partial_sum_x_offset,
            self.ec_op_ec_subset_sum_partial_sum_y_column,
            self.ec_op_ec_subset_sum_partial_sum_y_offset,
            self.ec_op_ec_subset_sum_selector_column,
            self.ec_op_ec_subset_sum_selector_offset,
            self.ec_op_ec_subset_sum_slope_column,
            self.ec_op_ec_subset_sum_slope_offset,
            self.ec_op_ec_subset_sum_x_diff_inv_column,
            self.ec_op_ec_subset_sum_x_diff_inv_offset,
            self.ec_op_m_suboffset,
            self.ec_op_p_x_suboffset,
            self.ec_op_p_y_suboffset,
            self.ec_op_q_x_suboffset,
            self.ec_op_q_y_suboffset,
            self.ec_op_r_x_suboffset,
            self.ec_op_r_y_suboffset,
            self.ec_op_builtin_row_ratio,
            self.ecdsa_message_suboffset,
            self.ecdsa_pubkey_suboffset,
            self.ecdsa_signature0_add_results_inv_column,
            self.ecdsa_signature0_add_results_inv_offset,
            self.ecdsa_signature0_add_results_slope_column,
            self.ecdsa_signature0_add_results_slope_offset,
            self.ecdsa_signature0_doubling_slope_column,
            self.ecdsa_signature0_doubling_slope_offset,
            self.ecdsa_signature0_exponentiate_generator_partial_sum_x_column,
            self.ecdsa_signature0_exponentiate_generator_partial_sum_x_offset,
            self.ecdsa_signature0_exponentiate_generator_partial_sum_y_column,
            self.ecdsa_signature0_exponentiate_generator_partial_sum_y_offset,
            self.ecdsa_signature0_exponentiate_generator_selector_column,
            self.ecdsa_signature0_exponentiate_generator_selector_offset,
            self.ecdsa_signature0_exponentiate_generator_slope_column,
            self.ecdsa_signature0_exponentiate_generator_slope_offset,
            self.ecdsa_signature0_exponentiate_generator_x_diff_inv_column,
            self.ecdsa_signature0_exponentiate_generator_x_diff_inv_offset,
            self.ecdsa_signature0_exponentiate_key_partial_sum_x_column,
            self.ecdsa_signature0_exponentiate_key_partial_sum_x_offset,
            self.ecdsa_signature0_exponentiate_key_partial_sum_y_column,
            self.ecdsa_signature0_exponentiate_key_partial_sum_y_offset,
            self.ecdsa_signature0_exponentiate_key_selector_column,
            self.ecdsa_signature0_exponentiate_key_selector_offset,
            self.ecdsa_signature0_exponentiate_key_slope_column,
            self.ecdsa_signature0_exponentiate_key_slope_offset,
            self.ecdsa_signature0_exponentiate_key_x_diff_inv_column,
            self.ecdsa_signature0_exponentiate_key_x_diff_inv_offset,
            self.ecdsa_signature0_extract_r_inv_column,
            self.ecdsa_signature0_extract_r_inv_offset,
            self.ecdsa_signature0_extract_r_slope_column,
            self.ecdsa_signature0_extract_r_slope_offset,
            self.ecdsa_signature0_key_points_x_column,
            self.ecdsa_signature0_key_points_x_offset,
            self.ecdsa_signature0_key_points_y_column,
            self.ecdsa_signature0_key_points_y_offset,
            self.ecdsa_signature0_q_x_squared_column,
            self.ecdsa_signature0_q_x_squared_offset,
            self.ecdsa_signature0_r_w_inv_column,
            self.ecdsa_signature0_r_w_inv_offset,
            self.ecdsa_signature0_z_inv_column,
            self.ecdsa_signature0_z_inv_offset,
            self.ecdsa_builtin_row_ratio,
            self.keccak_input_output_suboffset,
            self.keccak_keccak_diluted_column0_suboffset,
            self.keccak_keccak_diluted_column1_suboffset,
            self.keccak_keccak_diluted_column2_suboffset,
            self.keccak_keccak_diluted_column3_suboffset,
            self.keccak_keccak_parse_to_diluted_cumulative_sum_column,
            self.keccak_keccak_parse_to_diluted_cumulative_sum_offset,
            self.keccak_keccak_parse_to_diluted_final_reshaped_input_column,
            self.keccak_keccak_parse_to_diluted_final_reshaped_input_offset,
            self.keccak_keccak_parse_to_diluted_reshaped_intermediate_column,
            self.keccak_keccak_parse_to_diluted_reshaped_intermediate_offset,
            self.keccak_keccak_rotated_parity0_column,
            self.keccak_keccak_rotated_parity0_offset,
            self.keccak_keccak_rotated_parity1_column,
            self.keccak_keccak_rotated_parity1_offset,
            self.keccak_keccak_rotated_parity2_column,
            self.keccak_keccak_rotated_parity2_offset,
            self.keccak_keccak_rotated_parity3_column,
            self.keccak_keccak_rotated_parity3_offset,
            self.keccak_keccak_rotated_parity4_column,
            self.keccak_keccak_rotated_parity4_offset,
            self.keccak_row_ratio,
            self.mem_pool_addr_column,
            self.mem_pool_addr_offset,
            self.mem_pool_value_column,
            self.mem_pool_value_offset,
            self.memory_multi_column_perm_perm_cum_prod0_column,
            self.memory_multi_column_perm_perm_cum_prod0_offset,
            self.memory_sorted_addr_column,
            self.memory_sorted_addr_offset,
            self.memory_sorted_value_column,
            self.memory_sorted_value_offset,
            self.memory_units_row_ratio,
            self.mul_mod_a0_suboffset,
            self.mul_mod_a1_suboffset,
            self.mul_mod_a2_suboffset,
            self.mul_mod_a3_suboffset,
            self.mul_mod_a_offset_suboffset,
            self.mul_mod_b0_suboffset,
            self.mul_mod_b1_suboffset,
            self.mul_mod_b2_suboffset,
            self.mul_mod_b3_suboffset,
            self.mul_mod_b_offset_suboffset,
            self.mul_mod_c0_suboffset,
            self.mul_mod_c1_suboffset,
            self.mul_mod_c2_suboffset,
            self.mul_mod_c3_suboffset,
            self.mul_mod_c_offset_suboffset,
            self.mul_mod_carry0_part0_suboffset,
            self.mul_mod_carry0_part1_suboffset,
            self.mul_mod_carry0_part2_suboffset,
            self.mul_mod_carry0_part3_suboffset,
            self.mul_mod_carry0_part4_suboffset,
            self.mul_mod_carry0_part5_suboffset,
            self.mul_mod_carry0_part6_suboffset,
            self.mul_mod_carry1_part0_suboffset,
            self.mul_mod_carry1_part1_suboffset,
            self.mul_mod_carry1_part2_suboffset,
            self.mul_mod_carry1_part3_suboffset,
            self.mul_mod_carry1_part4_suboffset,
            self.mul_mod_carry1_part5_suboffset,
            self.mul_mod_carry1_part6_suboffset,
            self.mul_mod_carry2_part0_suboffset,
            self.mul_mod_carry2_part1_suboffset,
            self.mul_mod_carry2_part2_suboffset,
            self.mul_mod_carry2_part3_suboffset,
            self.mul_mod_carry2_part4_suboffset,
            self.mul_mod_carry2_part5_suboffset,
            self.mul_mod_carry2_part6_suboffset,
            self.mul_mod_carry3_part0_suboffset,
            self.mul_mod_carry3_part1_suboffset,
            self.mul_mod_carry3_part2_suboffset,
            self.mul_mod_carry3_part3_suboffset,
            self.mul_mod_carry3_part4_suboffset,
            self.mul_mod_carry3_part5_suboffset,
            self.mul_mod_carry3_part6_suboffset,
            self.mul_mod_carry4_part0_suboffset,
            self.mul_mod_carry4_part1_suboffset,
            self.mul_mod_carry4_part2_suboffset,
            self.mul_mod_carry4_part3_suboffset,
            self.mul_mod_carry4_part4_suboffset,
            self.mul_mod_carry4_part5_suboffset,
            self.mul_mod_carry4_part6_suboffset,
            self.mul_mod_carry5_part0_suboffset,
            self.mul_mod_carry5_part1_suboffset,
            self.mul_mod_carry5_part2_suboffset,
            self.mul_mod_carry5_part3_suboffset,
            self.mul_mod_carry5_part4_suboffset,
            self.mul_mod_carry5_part5_suboffset,
            self.mul_mod_carry5_part6_suboffset,
            self.mul_mod_n_suboffset,
            self.mul_mod_offsets_ptr_suboffset,
            self.mul_mod_p0_suboffset,
            self.mul_mod_p1_suboffset,
            self.mul_mod_p2_suboffset,
            self.mul_mod_p3_suboffset,
            self.mul_mod_p_multiplier0_part0_suboffset,
            self.mul_mod_p_multiplier0_part1_suboffset,
            self.mul_mod_p_multiplier0_part2_suboffset,
            self.mul_mod_p_multiplier0_part3_suboffset,
            self.mul_mod_p_multiplier0_part4_suboffset,
            self.mul_mod_p_multiplier0_part5_suboffset,
            self.mul_mod_p_multiplier1_part0_suboffset,
            self.mul_mod_p_multiplier1_part1_suboffset,
            self.mul_mod_p_multiplier1_part2_suboffset,
            self.mul_mod_p_multiplier1_part3_suboffset,
            self.mul_mod_p_multiplier1_part4_suboffset,
            self.mul_mod_p_multiplier1_part5_suboffset,
            self.mul_mod_p_multiplier2_part0_suboffset,
            self.mul_mod_p_multiplier2_part1_suboffset,
            self.mul_mod_p_multiplier2_part2_suboffset,
            self.mul_mod_p_multiplier2_part3_suboffset,
            self.mul_mod_p_multiplier2_part4_suboffset,
            self.mul_mod_p_multiplier2_part5_suboffset,
            self.mul_mod_p_multiplier3_part0_suboffset,
            self.mul_mod_p_multiplier3_part1_suboffset,
            self.mul_mod_p_multiplier3_part2_suboffset,
            self.mul_mod_p_multiplier3_part3_suboffset,
            self.mul_mod_p_multiplier3_part4_suboffset,
            self.mul_mod_p_multiplier3_part5_suboffset,
            self.mul_mod_row_ratio,
            self.mul_mod_values_ptr_suboffset,
            self.num_columns_first,
            self.num_columns_second,
            self.orig_public_memory_suboffset,
            self.pedersen_hash0_ec_subset_sum_bit_unpacking_prod_ones192_column,
            self.pedersen_hash0_ec_subset_sum_bit_unpacking_prod_ones192_offset,
            self.pedersen_hash0_ec_subset_sum_bit_unpacking_prod_ones196_column,
            self.pedersen_hash0_ec_subset_sum_bit_unpacking_prod_ones196_offset,
            self.pedersen_hash0_ec_subset_sum_partial_sum_x_column,
            self.pedersen_hash0_ec_subset_sum_partial_sum_x_offset,
            self.pedersen_hash0_ec_subset_sum_partial_sum_y_column,
            self.pedersen_hash0_ec_subset_sum_partial_sum_y_offset,
            self.pedersen_hash0_ec_subset_sum_selector_column,
            self.pedersen_hash0_ec_subset_sum_selector_offset,
            self.pedersen_hash0_ec_subset_sum_slope_column,
            self.pedersen_hash0_ec_subset_sum_slope_offset,
            self.pedersen_input0_suboffset,
            self.pedersen_input1_suboffset,
            self.pedersen_output_suboffset,
            self.pedersen_builtin_row_ratio,
            self.poseidon_param_0_input_output_suboffset,
            self.poseidon_param_1_input_output_suboffset,
            self.poseidon_param_2_input_output_suboffset,
            self.poseidon_poseidon_full_rounds_state0_column,
            self.poseidon_poseidon_full_rounds_state0_offset,
            self.poseidon_poseidon_full_rounds_state0_squared_column,
            self.poseidon_poseidon_full_rounds_state0_squared_offset,
            self.poseidon_poseidon_full_rounds_state1_column,
            self.poseidon_poseidon_full_rounds_state1_offset,
            self.poseidon_poseidon_full_rounds_state1_squared_column,
            self.poseidon_poseidon_full_rounds_state1_squared_offset,
            self.poseidon_poseidon_full_rounds_state2_column,
            self.poseidon_poseidon_full_rounds_state2_offset,
            self.poseidon_poseidon_full_rounds_state2_squared_column,
            self.poseidon_poseidon_full_rounds_state2_squared_offset,
            self.poseidon_poseidon_partial_rounds_state0_column,
            self.poseidon_poseidon_partial_rounds_state0_offset,
            self.poseidon_poseidon_partial_rounds_state0_squared_column,
            self.poseidon_poseidon_partial_rounds_state0_squared_offset,
            self.poseidon_poseidon_partial_rounds_state1_column,
            self.poseidon_poseidon_partial_rounds_state1_offset,
            self.poseidon_poseidon_partial_rounds_state1_squared_column,
            self.poseidon_poseidon_partial_rounds_state1_squared_offset,
            self.poseidon_row_ratio,
            self.range_check16_perm_cum_prod0_column,
            self.range_check16_perm_cum_prod0_offset,
            self.range_check16_sorted_column,
            self.range_check16_sorted_offset,
            self.range_check16_pool_column,
            self.range_check16_pool_offset,
            self.range_check96_builtin_inner_range_check0_suboffset,
            self.range_check96_builtin_inner_range_check1_suboffset,
            self.range_check96_builtin_inner_range_check2_suboffset,
            self.range_check96_builtin_inner_range_check3_suboffset,
            self.range_check96_builtin_inner_range_check4_suboffset,
            self.range_check96_builtin_inner_range_check5_suboffset,
            self.range_check96_builtin_mem_suboffset,
            self.range_check96_builtin_row_ratio,
            self.range_check_builtin_inner_range_check_suboffset,
            self.range_check_builtin_mem_suboffset,
            self.range_check_builtin_row_ratio,
            self.range_check_units_row_ratio,
            self.uses_add_mod_builtin,
            self.uses_bitwise_builtin,
            self.uses_ec_op_builtin,
            self.uses_ecdsa_builtin,
            self.uses_keccak_builtin,
            self.uses_mul_mod_builtin,
            self.uses_pedersen_builtin,
            self.uses_poseidon_builtin,
            self.uses_range_check96_builtin,
            self.uses_range_check_builtin,
        ]
        .into_iter()
    }
}
