#![no_std]

use funvec::{FunVec, FUNVEC_COLUMN_VALUES, FUNVEC_QUERIES};
use starknet_crypto::Felt;
use vector::types::{Query, QueryWithDepth};

extern crate alloc;

#[cfg(feature = "std")]
extern crate std;

pub mod table;
pub mod vector;

#[derive(Debug, Clone, Copy, Default)]
pub struct CacheCommitment {
    pub verify_oods: FunVec<Felt, 34>,
    pub vector_queries: FunVec<Query, FUNVEC_QUERIES>, // Initialized based on values.
    // Tree structure with queries with original queries on the left.
    pub shifted_queries: FunVec<QueryWithDepth, { FUNVEC_QUERIES * 3 }>, // Uninitialized.
    pub points: FunVec<Felt, FUNVEC_QUERIES>,                            // Uninitialized.
    pub eval_oods: CacheEvalOods,
}

#[derive(Debug, Clone, Copy, Default)]
pub struct CacheEvalOods {
    pub evaluations: FunVec<Felt, FUNVEC_QUERIES>,
    // n_original_columns + n_interaction_columns + Layout::CONSTRAINT_DEGREE
    pub column_values: FunVec<Felt, FUNVEC_COLUMN_VALUES>,
    pub powers: FunVec<Felt, 72>, // Based on `autogenerated_oods.rs`
}

unsafe impl bytemuck::Pod for CacheCommitment {}
unsafe impl bytemuck::Zeroable for CacheCommitment {}
