name: Manual Publish to Docker Hub

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Docker image version"
        required: true
        default: "latest"

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create remote builder certificates files
        run: |
          echo "${{ secrets.BUILDKIT_CA_PEM }}" > client-ca.pem
          echo "${{ secrets.BUILDKIT_CERT_PEM }}" > client-cert.pem
          echo "${{ secrets.BUILDKIT_KEY_PEM }}" > client-key.pem

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: remote
          endpoint: "tcp://buildkit.iosis.tech:30500"
          driver-opts: |
            cacert=${{ github.workspace }}/client-ca.pem
            cert=${{ github.workspace }}/client-cert.pem
            key=${{ github.workspace }}/client-key.pem
          cleanup: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: runtime.dockerfile
          tags: "okm165/swiftness:${{ github.event.inputs.version }}"
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
